# Generated by Django 6.0.6 on 2026-07-01 04:11

import afn_service_management.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('notifications', '0001_initial'), ('notifications', '0002_initial'), ('notifications', '0003_notificationtemplate_alter_notification_options_and_more'), ('notifications', '0004_alter_notification_type_firebasetoken'), ('notifications', '0005_remove_firebasetoken_notificatio_user_id_1bb9fb_idx_and_more'), ('notifications', '0006_remove_notification_send_sms_and_more'), ('notifications', '0007_alter_notification_id_alter_notificationlog_id_and_more'), ('notifications', '0008_alter_notificationtemplate_variables')]

    initial = True

    dependencies = [
        ('services', '0004_alter_servicetype_options_demandforecast_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(db_column='notification_template_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('variables', afn_service_management.fields.StructuredTextField(default=list, help_text="e.g., ['technician_name', 'service_type']", structure='list')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(db_column='notification_id', primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('ticket_assigned', 'Ticket Assigned'), ('status_update', 'Status Update'), ('reminder', 'Reminder'), ('urgent', 'Urgent Alert'), ('task_completed', 'Task Completed'), ('customer_inquiry', 'Customer Inquiry'), ('message', 'New Message'), ('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='message', max_length=50)),
                ('status', models.CharField(default='unread', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('email_sent', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='services.servicerequest')),
                ('send_email', models.BooleanField(default=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='services.serviceticket')),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(db_column='notification_log_id', primary_key=True, serialize=False)),
                ('email_status', models.CharField(default='pending', max_length=50)),
                ('email_response', models.TextField(blank=True, null=True)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='notifications.notification')),
            ],
        ),
    ]
