# Generated by Django 6.0.3 on 2026-06-09 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type_firebasetoken'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='firebasetoken',
            name='notificatio_user_id_1bb9fb_idx',
        ),
        migrations.DeleteModel(
            name='FirebaseToken',
        ),
    ]
