# Generated by Django 5.2.13 on 2026-06-15 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_firebasetoken_notificatio_user_id_1bb9fb_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='send_sms',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sms_sent',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='sms_response',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='sms_status',
        ),
    ]
