# Generated by Django 6.0.3 on 2026-06-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_remove_notification_send_sms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(db_column='notification_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='id',
            field=models.BigAutoField(db_column='notification_log_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='id',
            field=models.BigAutoField(db_column='notification_template_id', primary_key=True, serialize=False),
        ),
    ]
