# Generated by Django 6.0.6 on 2026-07-01 04:05

import afn_service_management.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_id_alter_notificationlog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='variables',
            field=afn_service_management.fields.StructuredTextField(default=list, help_text="e.g., ['technician_name', 'service_type']", structure='list'),
        ),
    ]
