# Generated by Django 6.0.8 on 2026-08-31 10:03

from django.db import migrations


def require_empty_retired_notification_models(apps, schema_editor):
    database_alias = schema_editor.connection.alias
    model_names = ('NotificationTemplate', 'NotificationLog')
    populated = [
        model_name
        for model_name in model_names
        if apps.get_model('notifications', model_name).objects.using(database_alias).exists()
    ]
    if populated:
        raise RuntimeError(
            'Cannot retire populated notification support models: '
            + ', '.join(populated)
            + '. Export and review their records before retrying.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_squashed_0008_alter_notificationtemplate_variables'),
    ]

    operations = [
        migrations.RunPython(
            require_empty_retired_notification_models,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='notification',
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
        migrations.DeleteModel(
            name='NotificationLog',
        ),
    ]
