"""Generate the exhaustive, untangled single-page Chen ERD for the AFN paper."""

from __future__ import annotations

import html
import re
from collections import Counter
from dataclasses import dataclass
from math import ceil
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
DBML_PATH = REPOSITORY_ROOT / "docs" / "models" / "AFN_ERD.dbml"
DRAWIO_PATH = REPOSITORY_ROOT / "docs" / "models" / "AFN_ERD_CHEN_PRESENTATION.drawio"
CURRENT_DRAWIO_PATH = REPOSITORY_ROOT / "docs" / "models" / "ERD_CURRENT.drawio"

GROUP_ORDER = [
    "Analytics",
    "After-Sales and Communication",
    "Identity, Access, Configuration and Audit",
    "Service Intake, Dispatch and Progress",
    "Field Evidence and Documents",
    "Inventory, Returns and Sales",
]
TABLE_ORDER = {
    "Identity, Access, Configuration and Audit": [
        "users_user", "users_clientprofile", "users_technicianprofile",
        "users_managementprofile", "users_usercapabilitygrant",
        "users_adminsettings", "users_landingpageasset", "users_activitylog",
        "users_changelog",
    ],
    "Service Intake, Dispatch and Progress": [
        "services_servicetype", "services_slarule", "services_servicerequest",
        "services_servicerequestservice", "services_servicelocation",
        "services_solarestimate", "services_serviceticket",
        "services_ticketcrewassignment", "services_servicestatushistory",
        "progress_ticketprogress", "services_technicianskill",
        "services_technicianlocationhistory", "services_arrivalvalidationlog",
    ],
    "Field Evidence and Documents": [
        "services_inspectionchecklist", "services_generateddocument",
        "services_technicaldatasheet", "services_solarcommissioningchecklist",
        "services_turnoveracceptance", "services_quotationrecord",
        "services_installationcontract", "services_solarprojectprofile",
        "services_fieldservicereport", "services_installedequipment",
    ],
    "Inventory, Returns and Sales": [
        "inventory_inventorycategory", "inventory_inventoryitem",
        "inventory_servicetypeinventoryrequirement",
        "inventory_inventoryreservation", "inventory_inventorytransaction",
        "inventory_equipmentreturnrequest",
        "inventory_equipmentreturnrequestitem", "services_salesrecord",
        "services_salesrecordline",
    ],
    "After-Sales and Communication": [
        "services_aftersalescase", "services_aftersalescaseevent",
        "services_maintenanceschedule", "messages_app_customersupportcase",
        "messages_app_message", "notifications_notification",
    ],
    "Analytics": [
        "services_serviceanalytics", "services_technicianperformance",
        "services_demandforecast", "services_servicetrend",
    ],
}

RELATIONSHIP_LABELS = {
    "user": "BELONGS TO", "client": "OWNED BY", "technician": "ASSIGNED TO",
    "assigned_admin": "MANAGED BY", "assigned_to": "ASSIGNED TO",
    "created_by": "CREATED BY", "updated_by": "UPDATED BY",
    "changed_by": "CHANGED BY", "submitted_by": "SUBMITTED BY",
    "completed_by": "COMPLETED BY", "prepared_by": "PREPARED BY",
    "reviewed_by": "REVIEWED BY", "performed_by": "PERFORMED BY",
    "generated_by": "GENERATED BY", "finalized_by": "FINALIZED BY",
    "confirmed_by": "CONFIRMED BY", "voided_by": "VOIDED BY",
    "granted_by": "GRANTED BY", "uploaded_by": "UPLOADED BY",
    "actor": "PERFORMED BY", "sender": "SENT BY", "receiver": "RECEIVED BY",
    "request": "FOR REQUEST", "service_request": "FROM REQUEST",
    "service_type": "USES SERVICE", "ticket": "FOR TICKET",
    "service_ticket": "FOR TICKET", "original_ticket": "ORIGINATES FROM",
    "item": "USES ITEM", "inventory_item": "USES ITEM",
    "category": "IN CATEGORY", "parent": "HAS PARENT", "case": "FOR CASE",
    "return_request": "CONTAINS", "sales_record": "CONTAINS",
    "quotation": "BASED ON", "installed_equipment": "USES EQUIPMENT",
    "generated_document": "USES DOCUMENT", "location": "AT LOCATION",
    "replaces": "REPLACES",
    "location_validation_updated_by": "LOCATION SETTINGS UPDATED BY",
}

TABLE_RE = re.compile(r"^Table\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{")
FIELD_RE = re.compile(r"^\s{2}([A-Za-z_][A-Za-z0-9_]*)\s+([^\[]+?)(?:\s+\[(.*)\])?\s*$")
REFERENCE_RE = re.compile(
    r"ref:\s*([>-])\s*([A-Za-z_][A-Za-z0-9_]*)\.([A-Za-z_][A-Za-z0-9_]*)"
)


@dataclass(frozen=True)
class Attribute:
    name: str
    primary_key: bool


@dataclass(frozen=True)
class Relationship:
    source_table: str
    source_field: str
    target_table: str
    target_field: str
    one_to_one: bool
    optional: bool


def parse_dbml(source: str) -> tuple[dict[str, list[Attribute]], list[Relationship]]:
    """Read entities, attributes, and inline references from the physical DBML."""
    tables: dict[str, list[Attribute]] = {}
    relationships: list[Relationship] = []
    current_table: str | None = None
    in_indexes = False

    for line in source.splitlines():
        table_match = TABLE_RE.match(line)
        if table_match:
            current_table = table_match.group(1)
            tables[current_table] = []
            in_indexes = False
            continue
        if current_table is None:
            continue
        if line.strip() == "Indexes {":
            in_indexes = True
            continue
        if line == "}":
            if in_indexes:
                in_indexes = False
            else:
                current_table = None
            continue
        if in_indexes or not line.startswith("  "):
            continue

        field_match = FIELD_RE.match(line)
        if not field_match:
            continue
        field_name, _field_type, options = field_match.groups()
        options = options or ""
        tables[current_table].append(Attribute(field_name, "pk" in options.split(", ")))
        reference_match = REFERENCE_RE.search(options)
        if reference_match:
            operator, target_table, target_field = reference_match.groups()
            relationships.append(Relationship(
                current_table, field_name, target_table, target_field,
                operator == "-", "not null" not in options,
            ))

    ordered_tables = {table for group in GROUP_ORDER for table in TABLE_ORDER[group]}
    if set(tables) != ordered_tables:
        missing = sorted(ordered_tables - set(tables))
        extra = sorted(set(tables) - ordered_tables)
        raise RuntimeError(f"DBML/table order mismatch; missing={missing}, extra={extra}")
    if any(relation.target_table not in tables for relation in relationships):
        raise RuntimeError("DBML contains a relationship outside the AFN application boundary")
    return tables, relationships


def cell(cell_id: str, value: str, style: str, x: int, y: int, width: int, height: int) -> str:
    return (
        f'        <mxCell id="{cell_id}" parent="1" style="{style}" '
        f'value="{html.escape(value, quote=True)}" vertex="1">\n'
        f'          <mxGeometry x="{x}" y="{y}" width="{width}" height="{height}" as="geometry" />\n'
        "        </mxCell>"
    )


def edge(
    cell_id: str, source: str, target: str, value: str, color: str,
    connection_style: str = "",
) -> str:
    style = (
        "edgeStyle=none;rounded=0;html=1;endArrow=none;startArrow=none;"
        f"labelBackgroundColor=#FFFFFF;strokeColor={color};fontSize=10;{connection_style}"
    )
    return (
        f'        <mxCell id="{cell_id}" edge="1" parent="1" source="{source}" '
        f'target="{target}" style="{style}" value="{html.escape(value, quote=True)}">\n'
        '          <mxGeometry relative="1" as="geometry" />\n'
        "        </mxCell>"
    )


def routed_edge(
    cell_id: str,
    source: str,
    target: str,
    value: str,
    exit_x: float,
    entry_x: float,
    entry_y: float,
    waypoints: list[tuple[float, float]],
) -> str:
    points = "\n".join(
        f'              <mxPoint x="{x:.2f}" y="{y:.2f}" />'
        for x, y in waypoints
    )
    style = (
        "edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;"
        "html=1;endArrow=none;startArrow=none;jumpStyle=arc;jumpSize=10;"
        "strokeColor=#000000;strokeWidth=1.3;labelBackgroundColor=#FFFFFF;"
        "fontSize=11;fontStyle=1;"
        f"exitX={exit_x:.4f};exitY=1;exitPerimeter=1;entryX={entry_x:.1f};"
        f"entryY={entry_y:.2f};entryPerimeter=1;"
    )
    return (
        f'        <mxCell id="{cell_id}" edge="1" parent="1" source="{source}" '
        f'target="{target}" style="{style}" value="{html.escape(value, quote=True)}">\n'
        '          <mxGeometry relative="1" as="geometry">\n'
        '            <Array as="points">\n'
        f"{points}\n"
        '            </Array>\n'
        '          </mxGeometry>\n'
        "        </mxCell>"
    )


def display_name(table_name: str) -> str:
    prefixes = ("messages_app_", "notifications_", "inventory_", "progress_", "services_", "users_")
    for prefix in prefixes:
        if table_name.startswith(prefix):
            table_name = table_name[len(prefix):]
            break
    return table_name.replace("_", " ").upper()


def relationship_title(field_name: str) -> str:
    logical_name = field_name[:-3] if field_name.endswith("_id") else field_name
    return RELATIONSHIP_LABELS.get(logical_name, f"HAS {logical_name.replace('_', ' ').upper()}")


def generate() -> str:
    tables, relationships = parse_dbml(DBML_PATH.read_text(encoding="utf-8"))

    page_margin = 80
    column_width = 2700
    entity_width = 380
    entity_height = 56
    attribute_width = 380
    attribute_height = 30
    attribute_step = 40
    first_y = 205
    page_width = page_margin * 2 + len(GROUP_ORDER) * column_width
    nodes: list[str] = []
    edges: list[str] = []
    group_extents: dict[str, tuple[int, int, int, int]] = {}
    entity_layout: dict[str, tuple[int, int, int, int]] = {}
    entity_attribute_tops: dict[str, int] = {}
    entity_clear_routes: dict[str, int] = {}

    styles = {
        "entity": "rounded=0;whiteSpace=wrap;html=1;fillColor=#B7E36D;strokeColor=#000000;fontStyle=0;fontSize=12;strokeWidth=1.2;",
        "entity_ref": "rounded=0;whiteSpace=wrap;html=1;fillColor=#B7E36D;strokeColor=#000000;fontStyle=0;fontSize=10;strokeWidth=1.2;",
        "attribute": "ellipse;whiteSpace=wrap;html=1;fillColor=#FFD966;strokeColor=#000000;fontSize=9;strokeWidth=1;",
        "relationship": "rhombus;whiteSpace=wrap;html=1;fillColor=#F6B26B;strokeColor=#000000;fontSize=10;fontStyle=0;strokeWidth=1.3;",
        "header": "rounded=0;whiteSpace=wrap;html=1;fillColor=#DCE6F1;strokeColor=#3D85C6;fontSize=14;fontStyle=1;strokeWidth=1.5;",
        "group": "rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#CBD5E1;dashed=1;verticalAlign=top;spacingTop=10;",
        "note": "rounded=1;whiteSpace=wrap;html=1;fillColor=#F8FAFC;strokeColor=#94A3B8;fontSize=12;fontColor=#334155;align=left;spacing=12;",
    }

    degree: Counter[str] = Counter()
    for relation in relationships:
        degree.update((relation.source_table, relation.target_table))
    layout_order: dict[str, list[str]] = {}
    for group_name in GROUP_ORDER:
        ranked = sorted(TABLE_ORDER[group_name], key=lambda table: (-degree[table], table))
        slot_priority = sorted(
            range(len(ranked)),
            key=lambda slot: (abs(slot - (len(ranked) - 1) / 2), slot),
        )
        arranged = [""] * len(ranked)
        for table_name, slot in zip(ranked, slot_priority, strict=True):
            arranged[slot] = table_name
        layout_order[group_name] = arranged

    entity_section_bottom = first_y
    for group_index, group_name in enumerate(GROUP_ORDER):
        group_x = page_margin + group_index * column_width
        entity_x = group_x + (column_width - entity_width) // 2
        current_y = first_y
        for table_name in layout_order[group_name]:
            row_count = ceil(len(tables[table_name]) / 2)
            attribute_area_height = max(70, row_count * attribute_step)
            entity_y = current_y + max(0, (attribute_area_height - entity_height) // 2)
            entity_layout[table_name] = (entity_x, entity_y, entity_width, entity_height)
            entity_attribute_tops[table_name] = current_y
            entity_clear_routes[table_name] = current_y + attribute_area_height + 28
            current_y += attribute_area_height + 105
        group_height = current_y - 150
        group_extents[group_name] = (group_x, 105, column_width - 50, group_height)
        entity_section_bottom = max(entity_section_bottom, 105 + group_height)

    for group_index, group_name in enumerate(GROUP_ORDER):
        gx, gy, gw, gh = group_extents[group_name]
        nodes.append(cell(f"group_{group_index}", "", styles["group"], gx, gy, gw, gh))
        nodes.append(cell(f"header_{group_index}", group_name.upper(), styles["header"], gx + 20, 125, gw - 40, 48))
        for table_name in layout_order[group_name]:
            entity_x, entity_y, width, height = entity_layout[table_name]
            entity_id = f"entity_{table_name}"
            nodes.append(cell(entity_id, display_name(table_name), styles["entity"], entity_x, entity_y, width, height))
            for index, attribute in enumerate(tables[table_name]):
                row, side = divmod(index, 2)
                attr_x = entity_x - attribute_width - 70 if side == 0 else entity_x + width + 70
                attr_y = entity_attribute_tops[table_name] + row * attribute_step
                label = f"<u>{attribute.name}</u>" if attribute.primary_key else attribute.name
                attr_id = f"attr_{table_name}_{attribute.name}"
                nodes.append(cell(attr_id, label, styles["attribute"], attr_x, attr_y, attribute_width, attribute_height))
                connection = (
                    "exitX=1;exitY=0.5;entryX=0;entryY=0.5;"
                    if side == 0 else
                    "exitX=0;exitY=0.5;entryX=1;entryY=0.5;"
                )
                edges.append(edge(f"ae_{table_name}_{index}", attr_id, entity_id, "", "#000000", connection))

    relationship_top = entity_section_bottom + 120
    nodes.append(cell(
        "relationship_header",
        "DIRECT CHEN RELATIONSHIPS — EVERY DIAMOND CONNECTS TO THE CANONICAL ENTITIES ABOVE",
        styles["header"], page_margin, relationship_top,
        page_width - page_margin * 2, 54,
    ))
    nodes.append(cell(
        "relationship_note",
        "Every direct connection has one stable identifier (R001-R102) printed on both legs and its diamond. Each diamond also names both endpoint entities, fields, and cardinalities, so a relationship remains readable without visually tracing a long rail. Bridge arcs distinguish intersections.",
        styles["note"], page_margin, relationship_top + 70,
        page_width - page_margin * 2, 58,
    ))

    def entity_center_x(table_name: str) -> float:
        x, _y, width, _height = entity_layout[table_name]
        return x + width / 2

    ordered_relationships = sorted(
        relationships,
        key=lambda relation: (
            abs(entity_center_x(relation.source_table) - entity_center_x(relation.target_table)),
            relation.source_table,
            relation.source_field,
        ),
    )
    relationship_row_height = 74
    relationship_start_y = relationship_top + 160
    diamond_width = 500
    diamond_height = 62
    group_by_table = {
        table_name: group_name
        for group_name in GROUP_ORDER
        for table_name in TABLE_ORDER[group_name]
    }
    routing_trunks = {
        group_name: group_extents[group_name][0] + column_width - 25
        for group_name in GROUP_ORDER
    }
    for index, relation in enumerate(ordered_relationships):
        relationship_code = f"R{index + 1:03d}"
        source_cardinality = "0..1" if relation.one_to_one and relation.optional else "1" if relation.one_to_one else "N"
        source_group = group_by_table[relation.source_table]
        target_group = group_by_table[relation.target_table]
        source_trunk_x = routing_trunks[source_group]
        target_trunk_x = routing_trunks[target_group]
        preferred_center_x = (source_trunk_x + target_trunk_x) / 2
        minimum_center_x = page_margin + diamond_width / 2 + 20
        maximum_center_x = page_width - page_margin - diamond_width / 2 - 20
        candidate_centers = [
            preferred_center_x + offset
            for distance in range(0, 1901, 380)
            for offset in ((-distance, distance) if distance else (0,))
        ]
        diamond_center_x = next(
            candidate
            for candidate in candidate_centers
            if minimum_center_x <= candidate <= maximum_center_x
            and all(
                abs(candidate - trunk_x) >= diamond_width / 2 + 50
                for trunk_x in routing_trunks.values()
            )
        )
        diamond_x = diamond_center_x - diamond_width / 2
        diamond_y = relationship_start_y + index * relationship_row_height
        source_rail_y = diamond_y + diamond_height * 0.28
        target_rail_y = diamond_y + diamond_height * 0.72
        diamond_id = f"relationship_{index}"
        nodes.append(cell(
            diamond_id,
            (
                f"<b>{relationship_code} · {relationship_title(relation.source_field)}</b><br>"
                f"{display_name(relation.source_table)}.{relation.source_field} ({source_cardinality})"
                f" → {display_name(relation.target_table)}.{relation.target_field} (1)"
            ),
            styles["relationship"],
            int(diamond_x), diamond_y, diamond_width, diamond_height,
        ))

        source_entity_x, source_entity_y, source_width, source_height = entity_layout[relation.source_table]
        target_entity_x, target_entity_y, target_width, target_height = entity_layout[relation.target_table]
        source_center_x = source_entity_x + source_width / 2
        target_center_x = target_entity_x + target_width / 2
        source_clear_y = entity_clear_routes[relation.source_table]
        target_clear_y = entity_clear_routes[relation.target_table]
        source_entry_x = 0.0 if source_trunk_x < diamond_center_x else 1.0
        target_entry_x = 0.0 if target_trunk_x < diamond_center_x else 1.0
        edges.append(routed_edge(
            f"re_{index}_source",
            f"entity_{relation.source_table}",
            diamond_id,
            f"{relationship_code} · {source_cardinality}",
            0.5,
            source_entry_x,
            0.28,
            [
                (source_center_x, source_clear_y),
                (source_trunk_x, source_clear_y),
                (source_trunk_x, source_rail_y),
            ],
        ))
        edges.append(routed_edge(
            f"re_{index}_target",
            f"entity_{relation.target_table}",
            diamond_id,
            f"{relationship_code} · 1",
            0.5,
            target_entry_x,
            0.72,
            [
                (target_center_x, target_clear_y),
                (target_trunk_x, target_clear_y),
                (target_trunk_x, target_rail_y),
            ],
        ))

    legend_y = relationship_start_y + len(ordered_relationships) * relationship_row_height + 70
    nodes.extend([
        cell("legend_entity", "ENTITY", styles["entity_ref"], 100, legend_y + 8, 300, 48),
        cell("legend_relation", "RELATIONSHIP", styles["relationship"], 470, legend_y, 320, 68),
        cell("legend_attribute", "ATTRIBUTE", styles["attribute"], 860, legend_y + 10, 340, 38),
        cell(
            "scope_note",
            f"Complete DBML scope: {len(tables)} entities, {sum(len(attributes) for attributes in tables.values())} attributes, and {len(relationships)} relationships. Underlined attributes are primary keys; 1, 0..1, and N state cardinality.",
            "text;html=1;strokeColor=none;fillColor=none;fontSize=12;fontColor=#475569;align=left;",
            1300, legend_y + 8, 2500, 48,
        ),
    ])

    page_height = legend_y + 160
    body = "\n".join(nodes + edges)
    return f'''<mxfile host="Electron" agent="Codex" pages="1">
  <diagram id="afn-full-chen-erd" name="AFN Full Chen ERD">
    <mxGraphModel dx="2400" dy="1600" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="{page_width}" pageHeight="{page_height}" math="0" shadow="0">
      <root>
        <mxCell id="0" />
        <mxCell id="1" parent="0" />
        <mxCell id="title" parent="1" style="text;html=1;strokeColor=none;fillColor=none;align=center;fontSize=26;fontStyle=1" value="Entity Relationship Diagram of the AFN Service Management System" vertex="1">
          <mxGeometry x="{page_width // 2 - 900}" y="25" width="1800" height="45" as="geometry" />
        </mxCell>
{body}
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
'''


if __name__ == "__main__":
    diagram = generate()
    for output_path in (DRAWIO_PATH, CURRENT_DRAWIO_PATH):
        output_path.write_text(diagram, encoding="utf-8")
        print(f"Generated {output_path}")
