# Generated by Django 6.0.8 on 2026-08-31 10:03

from django.db import migrations


def require_empty_service_history(apps, schema_editor):
    ServiceHistory = apps.get_model('history', 'ServiceHistory')
    if ServiceHistory.objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError(
            'Cannot retire history.ServiceHistory while rows exist. '
            'Export and reconcile them with services.ServiceTicket history first.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_servicehistory_id'),
    ]

    operations = [
        migrations.RunPython(require_empty_service_history, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='ServiceHistory',
        ),
    ]
