# Generated by Django 6.0.6 on 2026-07-01 04:11

import afn_service_management.fields
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from datetime import timedelta


DEFAULT_RULES = [
    ('approval_delay', 180, 480),
    ('assignment_delay', 120, 360),
    ('start_delay', 15, 60),
    ('execution_delay', 90, 120),
    ('reschedule_delay', 240, 720),
]


def seed_sla_rules(apps, schema_editor):
    SLARule = apps.get_model('services', 'SLARule')
    for key, warning_minutes, overdue_minutes in DEFAULT_RULES:
        SLARule.objects.get_or_create(
            key=key,
            defaults={
                'warning_minutes': warning_minutes,
                'overdue_minutes': overdue_minutes,
                'is_active': True,
            },
        )


def update_existing_reminder_windows(apps, schema_editor):
    MaintenanceSchedule = apps.get_model('services', 'MaintenanceSchedule')
    for schedule in MaintenanceSchedule.objects.exclude(status__in=['completed', 'dismissed']):
        schedule.follow_up_window_days = 7
        schedule.notify_on_date = schedule.next_due_date - timedelta(days=7)
        schedule.save(update_fields=['follow_up_window_days', 'notify_on_date', 'updated_at'])


def copy_technical_data_sheet_fields(apps, schema_editor):
    TechnicalDataSheet = apps.get_model('services', 'TechnicalDataSheet')

    for record in TechnicalDataSheet.objects.all():
        record.ac_phase_power_supply = record.ac_phase or record.ac_phase_power_supply
        record.attachments_json = (
            {'items': record.attachments}
            if isinstance(record.attachments, list) and record.attachments
            else (record.attachments_json or {})
        )
        record.average_monthly_electric_bill = record.monthly_bill or record.average_monthly_electric_bill
        record.primary_electric_supply = record.electric_supply or record.primary_electric_supply
        record.load_schedule_json = record.load_schedule or record.load_schedule_json
        record.rooftop_type = record.roof_type or record.rooftop_type

        record.save(
            update_fields=[
                'ac_phase_power_supply',
                'attachments_json',
                'average_monthly_electric_bill',
                'primary_electric_supply',
                'load_schedule_json',
                'rooftop_type',
            ]
        )


def reverse_copy_technical_data_sheet_fields(apps, schema_editor):
    TechnicalDataSheet = apps.get_model('services', 'TechnicalDataSheet')

    for record in TechnicalDataSheet.objects.all():
        record.ac_phase = record.ac_phase_power_supply or record.ac_phase
        attachments = record.attachments_json or {}
        if isinstance(attachments, dict):
            record.attachments = attachments.get('items') or []
        elif isinstance(attachments, list):
            record.attachments = attachments
        record.monthly_bill = record.average_monthly_electric_bill or record.monthly_bill
        record.electric_supply = record.primary_electric_supply or record.electric_supply
        record.load_schedule = record.load_schedule_json or record.load_schedule
        record.roof_type = record.rooftop_type or record.roof_type

        record.save(
            update_fields=[
                'ac_phase',
                'attachments',
                'monthly_bill',
                'electric_supply',
                'load_schedule',
                'roof_type',
            ]
        )


ARRIVAL_INDEX_RENAMES = [
    (
        'services_arrival_ticket_idx',
        'services_ar_ticket__286470_idx',
        ['ticket', '-created_at'],
    ),
    (
        'services_arrival_tech_idx',
        'services_ar_technic_de004e_idx',
        ['technician', '-created_at'],
    ),
    (
        'services_arrival_action_idx',
        'services_ar_action_c6d1a7_idx',
        ['action', '-created_at'],
    ),
    (
        'services_arrival_result_idx',
        'services_ar_validat_308646_idx',
        ['validation_result', '-created_at'],
    ),
]


def _sync_arrival_validation_indexes(apps, schema_editor, *, forward):
    ArrivalValidationLog = apps.get_model('services', 'ArrivalValidationLog')
    table_name = ArrivalValidationLog._meta.db_table
    constraints = schema_editor.connection.introspection.get_constraints(
        schema_editor.connection.cursor(),
        table_name,
    )

    for old_name, new_name, fields in ARRIVAL_INDEX_RENAMES:
        source_name = old_name if forward else new_name
        target_name = new_name if forward else old_name
        current_constraints = constraints.keys()

        if target_name in current_constraints:
            continue

        if source_name in current_constraints:
            schema_editor.remove_index(
                ArrivalValidationLog,
                models.Index(fields=fields, name=source_name),
            )

        schema_editor.add_index(
            ArrivalValidationLog,
            models.Index(fields=fields, name=target_name),
        )
        constraints = schema_editor.connection.introspection.get_constraints(
            schema_editor.connection.cursor(),
            table_name,
        )


def rename_arrival_indexes_forward(apps, schema_editor):
    _sync_arrival_validation_indexes(apps, schema_editor, forward=True)


def rename_arrival_indexes_backward(apps, schema_editor):
    _sync_arrival_validation_indexes(apps, schema_editor, forward=False)

class Migration(migrations.Migration):

    replaces = [('services', '0001_initial'), ('services', '0002_initial'), ('services', '0003_servicerequest_auto_ticket_created_and_more'), ('services', '0004_alter_servicetype_options_demandforecast_and_more'), ('services', '0005_serviceticket_client_feedback_and_more'), ('services', '0006_serviceticket_route_distance_and_more'), ('services', '0007_serviceticket_created_at_serviceticket_updated_at_and_more'), ('services', '0008_aftersalescase'), ('services', '0009_alter_aftersalescase_assigned_to'), ('services', '0010_inspectionchecklist_maintenance_interval_days_and_more'), ('services', '0011_inspectionchecklist_proof_media_and_more'), ('services', '0012_aftersalescase_creation_source_and_checklist_handoff'), ('services', '0013_ticketcrewassignment_and_more'), ('services', '0014_serviceticket_completion_notes_and_more'), ('services', '0015_alter_servicerequest_options_and_more'), ('services', '0016_maintenanceschedule_client_notified_at'), ('services', '0017_add_servicetype_cost_limits_procedures'), ('services', '0018_aftersalescase_services_af_status_1919bc_idx_and_more'), ('services', '0019_inspectionchecklist_checklist_items_and_more'), ('services', '0020_inspectionchecklist_submitted_at_and_more'), ('services', '0021_alter_servicerequest_request_date'), ('services', '0022_admin_owned_management_workflows'), ('services', '0023_servicerequestservice'), ('services', '0024_servicerequest_request_source'), ('services', '0025_slarule'), ('services', '0026_rename_ticket_supervisor_to_assigned_admin'), ('services', '0027_rename_assigned_admin_ticket_indexes'), ('services', '0028_service_ticket_inspection_workflow_statuses'), ('services', '0029_remove_serviceticket_services_se_assigne_9052a0_idx_and_more'), ('services', '0030_maintenance_three_day_reminder'), ('services', '0031_servicetype_is_active'), ('services', '0032_remove_serviceticket_services_se_supervi_76c7e4_idx_and_more'), ('services', '0033_alter_slarule_key'), ('services', '0034_arrival_validation'), ('services', '0035_remove_arrivalvalidationlog_services_ar_ticket__286470_idx_and_more'), ('services', '0036_restore_arrival_validation_workflow'), ('services', '0037_rename_services_arrival_ticket_idx_services_ar_ticket__286470_idx_and_more'), ('services', '0038_solarcommissioningchecklist'), ('services', '0039_generateddocument'), ('services', '0040_serviceticket_project_details'), ('services', '0041_installedequipment'), ('services', '0042_quotationrecord'), ('services', '0043_turnoveracceptance_and_more'), ('services', '0044_technicaldatasheet'), ('services', '0045_installationcontract'), ('services', '0046_fieldservicereport_solarprojectprofile'), ('services', '0047_remove_technicaldatasheet_ac_phase_power_supply_and_more'), ('services', '0048_restore_canonical_technicaldatasheet'), ('services', '0049_alter_generateddocument_data_json_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('estimated_duration', models.IntegerField(default=60)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype')),
                ('auto_ticket_created', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time_slot', models.CharField(blank=True, choices=[('morning', 'Morning (8 AM - 11 AM)'), ('midday', 'Midday (11 AM - 2 PM)'), ('afternoon', 'Afternoon (2 PM - 5 PM)'), ('evening', 'Evening (5 PM - 8 PM)')], max_length=20, null=True)),
                ('scheduling_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='services.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicerequest')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_tickets', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('auto_assigned', models.BooleanField(default=False)),
                ('client_feedback', models.TextField(blank=True, null=True)),
                ('client_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=50)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('route_distance', models.FloatField(blank=True, null=True)),
                ('route_duration', models.FloatField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('reschedule_reason', models.TextField(blank=True, null=True)),
                ('reschedule_requested', models.BooleanField(default=False)),
                ('reschedule_requested_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_time_slot', models.CharField(blank=True, choices=[('morning', 'Morning (8 AM - 11 AM)'), ('midday', 'Midday (11 AM - 2 PM)'), ('afternoon', 'Afternoon (2 PM - 5 PM)'), ('evening', 'Evening (5 PM - 8 PM)')], max_length=20, null=True)),
                ('smart_assignment_score', models.FloatField(blank=True, null=True)),
                ('smart_assignment_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('warranty_notes', models.TextField(blank=True, null=True)),
                ('warranty_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('active', 'Active'), ('expired', 'Expired'), ('void', 'Void')], default='not_applicable', max_length=20)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('completion_proof_images', models.JSONField(blank=True, default=list, help_text='List of image URLs uploaded as proof of job completion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='services.serviceticket')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(default=0)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('forecast_period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('predicted_requests', models.IntegerField()),
                ('confidence_level', models.FloatField(default=0.8)),
                ('weather_impact', models.FloatField(default=0)),
                ('seasonal_trend', models.FloatField(default=0)),
                ('historical_average', models.IntegerField(default=0)),
                ('actual_requests', models.IntegerField(blank=True, null=True)),
                ('forecast_accuracy', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_demands', to='services.servicetype')),
            ],
            options={
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('seasonal', 'Seasonal'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('average_requests', models.FloatField()),
                ('peak_day', models.CharField(blank=True, max_length=20)),
                ('peak_hour', models.IntegerField(blank=True, null=True)),
                ('growth_rate', models.FloatField(default=0)),
                ('trend_direction', models.CharField(default='stable', max_length=20)),
                ('standard_deviation', models.FloatField(default=0)),
                ('confidence_interval', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_requests', models.IntegerField(default=0)),
                ('completed_requests', models.IntegerField(default=0)),
                ('pending_requests', models.IntegerField(default=0)),
                ('cancelled_requests', models.IntegerField(default=0)),
                ('avg_response_time_hours', models.FloatField(default=0)),
                ('avg_completion_time_hours', models.FloatField(default=0)),
                ('technician_utilization_rate', models.FloatField(default=0)),
                ('service_area_coverage', models.FloatField(default=0)),
                ('popular_locations', models.JSONField(default=list)),
                ('satisfaction_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicetype')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='TechnicianPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tickets_assigned', models.IntegerField(default=0)),
                ('tickets_completed', models.IntegerField(default=0)),
                ('tickets_pending', models.IntegerField(default=0)),
                ('total_work_hours', models.FloatField(default=0)),
                ('avg_response_time_hours', models.FloatField(default=0)),
                ('avg_completion_time_hours', models.FloatField(default=0)),
                ('customer_satisfaction', models.FloatField(default=0)),
                ('rework_rate', models.FloatField(default=0)),
                ('distance_traveled_km', models.FloatField(default=0)),
                ('fuel_efficiency', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('technician', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_profile', models.CharField(choices=[('commercial_area', 'Commercial Area'), ('dust_free_area', 'Dust-Free Area'), ('standard_area', 'Standard Area')], max_length=30)),
                ('interval_days', models.PositiveIntegerField()),
                ('follow_up_window_days', models.PositiveIntegerField(default=14)),
                ('last_service_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('notify_on_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('due_soon', 'Due Soon'), ('due', 'Due'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='scheduled', max_length=20)),
                ('maintenance_notes', models.TextField(blank=True, null=True)),
                ('due_soon_notified_at', models.DateTimeField(blank=True, null=True)),
                ('due_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to=settings.AUTH_USER_MODEL)),
                ('service_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedule', to='services.serviceticket')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='services.servicetype')),
                ('prediction_notes', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(default='normal', max_length=20)),
                ('risk_score', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['next_due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AfterSalesCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('follow_up', 'Follow Up'), ('maintenance', 'Maintenance'), ('complaint', 'Complaint'), ('warranty', 'Warranty'), ('revisit', 'Revisit'), ('feedback', 'Feedback')], default='follow_up', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('requires_revisit', models.BooleanField(default=False)),
                ('customer_satisfaction', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'follow_up'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_after_sales_cases', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='after_sales_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_after_sales_cases', to=settings.AUTH_USER_MODEL)),
                ('service_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_sales_cases', to='services.serviceticket')),
                ('creation_source', models.CharField(choices=[('manual', 'Manual'), ('completion_flow', 'Completion Flow'), ('maintenance_alert', 'Maintenance Alert')], default='manual', max_length=30)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('site_accessible', models.BooleanField(default=False)),
                ('site_accessible_notes', models.TextField(blank=True, null=True)),
                ('electrical_available', models.BooleanField(default=False)),
                ('electrical_adequate', models.BooleanField(default=False)),
                ('electrical_notes', models.TextField(blank=True, null=True)),
                ('roof_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('structural_assessment', models.TextField(blank=True, null=True)),
                ('safety_equipment_present', models.BooleanField(default=False)),
                ('safety_hazards', models.TextField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_inspections', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='services.serviceticket')),
                ('maintenance_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('maintenance_notes', models.TextField(blank=True, null=True)),
                ('maintenance_profile', models.CharField(blank=True, choices=[('commercial_area', 'Commercial Area'), ('dust_free_area', 'Dust-Free Area'), ('standard_area', 'Standard Area')], max_length=30, null=True)),
                ('maintenance_required', models.BooleanField(default=False)),
                ('proof_media', models.JSONField(blank=True, default=list)),
                ('warranty_notes', models.TextField(blank=True, null=True)),
                ('warranty_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('warranty_provided', models.BooleanField(default=False)),
                ('follow_up_case_type', models.CharField(blank=True, choices=[('follow_up', 'Follow Up'), ('complaint', 'Complaint'), ('warranty', 'Warranty'), ('revisit', 'Revisit'), ('feedback', 'Feedback')], max_length=20, null=True)),
                ('follow_up_details', models.TextField(blank=True, null=True)),
                ('follow_up_due_date', models.DateField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_summary', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketCrewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, related_name='crew_ticket_assignments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='services.serviceticket')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('ticket', 'technician'), name='unique_ticket_crew_assignment')],
            },
        ),
        migrations.CreateModel(
            name='TechnicianSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=50)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype')),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('technician', 'service_type')},
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['client_id', 'status'], name='services_se_client__2c6fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'request_date'], name='services_se_status_1c7dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['status', 'scheduled_date'], name='services_se_status_08448c_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['technician_id', 'status'], name='services_se_technic_7329e3_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['status', 'created_at'], name='services_se_status_51ab19_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['auto_assigned', 'assigned_at'], name='services_se_auto_as_db7434_idx'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='client_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated cost for this service type', max_digits=10),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='max_daily_assignments',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of this service type a technician can be assigned per day'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='procedures',
            field=models.JSONField(blank=True, default=list, help_text="Ordered list of procedure steps, e.g. [{'step': 1, 'title': '...', 'description': '...'}]"),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='required_equipment',
            field=models.JSONField(blank=True, default=list, help_text="List of required tools/equipment, e.g. [{'name': 'Drill', 'quantity': 1}]"),
        ),
        migrations.AddIndex(
            model_name='aftersalescase',
            index=models.Index(fields=['status', 'created_at'], name='services_af_status_1919bc_idx'),
        ),
        migrations.AddIndex(
            model_name='aftersalescase',
            index=models.Index(fields=['assigned_to', 'status'], name='services_af_assigne_12a36b_idx'),
        ),
        migrations.AddIndex(
            model_name='aftersalescase',
            index=models.Index(fields=['client', 'status'], name='services_af_client__fda154_idx'),
        ),
        migrations.AddIndex(
            model_name='aftersalescase',
            index=models.Index(fields=['due_date', 'status'], name='services_af_due_dat_d6d3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='demandforecast',
            index=models.Index(fields=['service_type', 'forecast_period', 'forecast_date'], name='services_de_service_276f44_idx'),
        ),
        migrations.AddIndex(
            model_name='demandforecast',
            index=models.Index(fields=['forecast_date'], name='services_de_forecas_9149d8_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['status', 'next_due_date'], name='services_ma_status_1756e8_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['client', 'status'], name='services_ma_client__4aa047_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['service_type', 'status'], name='services_ma_service_746c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceanalytics',
            index=models.Index(fields=['service_type', '-date'], name='services_se_service_777872_idx'),
        ),
        migrations.AddIndex(
            model_name='servicestatushistory',
            index=models.Index(fields=['ticket', '-timestamp'], name='services_se_ticket__2577de_idx'),
        ),
        migrations.AddIndex(
            model_name='servicestatushistory',
            index=models.Index(fields=['status', '-timestamp'], name='services_se_status_29b933_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['supervisor_id', 'status'], name='services_se_supervi_76c7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['supervisor_id', 'created_at'], name='services_se_supervi_45028b_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['completed_date'], name='services_se_complet_5a669e_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['scheduled_date', 'scheduled_time'], name='services_se_schedul_9cc62e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetrend',
            index=models.Index(fields=['service_type', 'trend_type', 'period_start', 'period_end'], name='services_se_service_81b7db_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianlocationhistory',
            index=models.Index(fields=['technician', '-timestamp'], name='services_te_technic_582174_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianlocationhistory',
            index=models.Index(fields=['-timestamp'], name='services_te_timesta_4b38af_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianperformance',
            index=models.Index(fields=['technician', '-date'], name='services_te_technic_dfe938_idx'),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='checklist_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='procedure_source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='required_equipment_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='service_type_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_inspection_checklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aftersalescase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['superadmin', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_after_sales_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['superadmin', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ServiceRequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='services.servicerequest')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='services.servicetype')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('request', 'service_type'), name='unique_service_type_per_request')],
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_source',
            field=models.CharField(choices=[('client_portal', 'Client Portal'), ('walk_in', 'Walk-in'), ('phone', 'Phone'), ('admin_created', 'Admin Created')], default='client_portal', max_length=30),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['request_source', 'request_date'], name='services_se_request_b828c5_idx'),
        ),
        migrations.CreateModel(
            name='SLARule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('approval_delay', 'Approval delay'), ('assignment_delay', 'Assignment delay'), ('start_delay', 'Start delay'), ('execution_delay', 'Execution delay'), ('reschedule_delay', 'Reschedule delay')], max_length=40, unique=True)),
                ('warning_minutes', models.PositiveIntegerField()),
                ('overdue_minutes', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.RunPython(code=seed_sla_rules, reverse_code=django.db.migrations.operations.special.RunPython.noop),
        migrations.RemoveIndex(
            model_name='serviceticket',
            name='services_se_supervi_76c7e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceticket',
            name='services_se_supervi_45028b_idx',
        ),
        migrations.RenameField(
            model_name='serviceticket',
            old_name='supervisor',
            new_name='assigned_admin',
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='assigned_admin',
            field=models.ForeignKey(limit_choices_to={'role__in': ['superadmin', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admin_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['assigned_admin_id', 'status'], name='services_se_assigne_9052a0_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['assigned_admin_id', 'created_at'], name='services_se_assigne_55e7bc_idx'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('For Inspection', 'For Inspection'), ('Inspection Completed', 'Inspection Completed'), ('Ready for Service', 'Ready for Service'), ('Awaiting Materials', 'Awaiting Materials'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=50),
        ),
        migrations.RemoveIndex(
            model_name='serviceticket',
            name='services_se_assigne_9052a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceticket',
            name='services_se_assigne_55e7bc_idx',
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['superadmin', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aftersalescase',
            name='id',
            field=models.BigAutoField(db_column='after_sales_case_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='id',
            field=models.BigAutoField(db_column='demand_forecast_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inspectionchecklist',
            name='id',
            field=models.BigAutoField(db_column='inspection_checklist_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='id',
            field=models.BigAutoField(db_column='maintenance_schedule_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceanalytics',
            name='id',
            field=models.BigAutoField(db_column='service_analytics_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicelocation',
            name='id',
            field=models.BigAutoField(db_column='service_location_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='id',
            field=models.BigAutoField(db_column='service_request_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicerequestservice',
            name='id',
            field=models.BigAutoField(db_column='service_request_service_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicestatushistory',
            name='id',
            field=models.BigAutoField(db_column='service_status_history_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='id',
            field=models.BigAutoField(db_column='service_ticket_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicetrend',
            name='id',
            field=models.BigAutoField(db_column='service_trend_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='id',
            field=models.BigAutoField(db_column='service_type_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='id',
            field=models.BigAutoField(db_column='sla_rule_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='technicianlocationhistory',
            name='id',
            field=models.BigAutoField(db_column='technician_location_history_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='technicianperformance',
            name='id',
            field=models.BigAutoField(db_column='technician_performance_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='technicianskill',
            name='id',
            field=models.BigAutoField(db_column='technician_skill_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticketcrewassignment',
            name='id',
            field=models.BigAutoField(db_column='ticket_crew_assignment_id', primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['supervisor_id', 'status'], name='services_se_supervi_76c7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['supervisor_id', 'created_at'], name='services_se_supervi_45028b_idx'),
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='assigned_admin',
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='follow_up_window_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='client_three_day_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='three_day_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=update_existing_reminder_windows,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='servicetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveIndex(
            model_name='serviceticket',
            name='services_se_supervi_76c7e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceticket',
            name='services_se_supervi_45028b_idx',
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='assigned_admin',
            field=models.ForeignKey(limit_choices_to={'role__in': ['superadmin', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admin_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='ticket_type',
            field=models.CharField(choices=[('inspection', 'Inspection'), ('installation', 'Installation')], default='installation', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('For Inspection', 'For Inspection'), ('Inspection Completed', 'Inspection Completed'), ('Ready for Service', 'Ready for Service'), ('Awaiting Materials', 'Awaiting Materials'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=50),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['assigned_admin_id', 'status'], name='services_se_assigne_9052a0_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['assigned_admin_id', 'created_at'], name='services_se_assigne_55e7bc_idx'),
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='supervisor',
        ),
        migrations.AlterField(
            model_name='slarule',
            name='key',
            field=models.CharField(choices=[('approval_delay', 'Approval delay'), ('assignment_delay', 'Assignment delay'), ('start_delay', 'Start delay'), ('execution_delay', 'Execution delay'), ('reschedule_delay', 'Reschedule delay'), ('inspection_delay', 'Inspection delay'), ('service_ready_delay', 'Service ready delay')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('For Inspection', 'For Inspection'), ('Inspection Completed', 'Inspection Completed'), ('Ready for Service', 'Ready for Service'), ('Awaiting Materials', 'Awaiting Materials'), ('Navigating', 'Navigating'), ('Arrived on Site', 'Arrived on Site'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=50),
        ),
        migrations.CreateModel(
            name='ArrivalValidationLog',
            fields=[
                ('id', models.BigAutoField(db_column='arrival_validation_log_id', primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('navigate', 'Navigate'), ('arrival_attempt', 'Arrival Attempt'), ('arrival_success', 'Arrival Success'), ('arrival_blocked', 'Arrival Blocked'), ('arrival_bypassed', 'Arrival Bypassed'), ('job_started', 'Job Started'), ('job_completed', 'Job Completed')], max_length=30)),
                ('technician_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('technician_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_meters', models.FloatField(blank=True, null=True)),
                ('validation_result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('bypassed', 'Bypassed'), ('not_required', 'Not Required')], default='not_required', max_length=20)),
                ('validation_enabled', models.BooleanField(default=True, help_text='Snapshot of whether location validation was enabled at time of action.')),
                ('radius_meters', models.PositiveSmallIntegerField(default=30, help_text='Snapshot of the allowed radius at time of action.')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_arrival_logs', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(blank=True, limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_validation_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_logs', to='services.serviceticket')),
            ],
            options={
                'verbose_name': 'Arrival Validation Log',
                'verbose_name_plural': 'Arrival Validation Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket', '-created_at'], name='services_arrival_ticket_idx'), models.Index(fields=['technician', '-created_at'], name='services_arrival_tech_idx'), models.Index(fields=['action', '-created_at'], name='services_arrival_action_idx'), models.Index(fields=['validation_result', '-created_at'], name='services_arrival_result_idx')],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rename_arrival_indexes_forward, rename_arrival_indexes_backward),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='arrivalvalidationlog',
                    new_name='services_ar_ticket__286470_idx',
                    old_name='services_arrival_ticket_idx',
                ),
                migrations.RenameIndex(
                    model_name='arrivalvalidationlog',
                    new_name='services_ar_technic_de004e_idx',
                    old_name='services_arrival_tech_idx',
                ),
                migrations.RenameIndex(
                    model_name='arrivalvalidationlog',
                    new_name='services_ar_action_c6d1a7_idx',
                    old_name='services_arrival_action_idx',
                ),
                migrations.RenameIndex(
                    model_name='arrivalvalidationlog',
                    new_name='services_ar_validat_308646_idx',
                    old_name='services_arrival_result_idx',
                ),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(db_column='generated_document_id', primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('field_service_report', 'Field Service Report'), ('turnover_acceptance', 'Turnover / Acceptance Form'), ('commissioning_checklist', 'PV Solar Site Commissioning Checklist'), ('technical_data_sheet', 'TDS - Technical Data Sheet'), ('installation_contract', 'Solar Installation Contract'), ('quotation_proposal', 'Quotation Proposal')], max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=32)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('source_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_service_documents', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='services.serviceticket')),
            ],
            options={
                'ordering': ['document_type'],
                'indexes': [models.Index(fields=['ticket', 'document_type'], name='services_ge_ticket__10c087_idx'), models.Index(fields=['document_type', '-updated_at'], name='services_ge_documen_e0fbd5_idx')],
                'constraints': [models.UniqueConstraint(fields=('ticket', 'document_type'), name='services_generated_document_unique_ticket_type')],
            },
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='project_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='InstalledEquipment',
            fields=[
                ('id', models.BigAutoField(db_column='installed_equipment_id', primary_key=True, serialize=False)),
                ('brand_model', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='installed_systems', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_equipment', to='services.serviceticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationRecord',
            fields=[
                ('id', models.BigAutoField(db_column='quotation_id', primary_key=True, serialize=False)),
                ('total_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('downpayment_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('balance_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('validity_days', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('bill_of_materials', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='services.serviceticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('For Inspection', 'For Inspection'), ('Inspection Completed', 'Inspection Completed'), ('Ready for Service', 'Ready for Service'), ('Awaiting Materials', 'Awaiting Materials'), ('Navigating', 'Navigating'), ('Arrived on Site', 'Arrived on Site'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Turned Over / Accepted', 'Turned Over / Accepted'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=50),
        ),
        migrations.CreateModel(
            name='SolarCommissioningChecklist',
            fields=[
                ('id', models.BigAutoField(db_column='solar_commissioning_checklist_id', primary_key=True, serialize=False)),
                ('site_name', models.CharField(blank=True, default='', max_length=255)),
                ('inverter_type', models.CharField(blank=True, default='', max_length=255)),
                ('system_designation', models.CharField(blank=True, default='', max_length=255)),
                ('inverter_serial_number', models.CharField(blank=True, default='', max_length=255)),
                ('commissioned_date', models.DateField(blank=True, null=True)),
                ('irradiance', models.CharField(blank=True, default='', max_length=100)),
                ('ambient_temperature', models.CharField(blank=True, default='', max_length=100)),
                ('readings_json', models.JSONField(blank=True, default=dict)),
                ('checklist_items_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_solar_commissioning_checklists', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solar_commissioning_checklist', to='services.serviceticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'commissioned_date'], name='services_so_status_b234c3_idx'), models.Index(fields=['ticket'], name='services_so_ticket__ef1e48_idx')],
            },
        ),
        migrations.CreateModel(
            name='TurnoverAcceptance',
            fields=[
                ('id', models.BigAutoField(db_column='turnover_acceptance_id', primary_key=True, serialize=False)),
                ('turnover_date', models.DateField(blank=True, null=True)),
                ('accepted_by_client_name', models.CharField(blank=True, default='', max_length=255)),
                ('accepted_by_client_contact', models.CharField(blank=True, default='', max_length=255)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('accepted', 'Accepted')], default='draft', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_turnover_acceptances', to=settings.AUTH_USER_MODEL)),
                ('generated_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnover_acceptances', to='services.generateddocument')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turnover_acceptance', to='services.serviceticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='services_tu_status_3ef3f8_idx'), models.Index(fields=['ticket'], name='services_tu_ticket__e6ef87_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstallationContract',
            fields=[
                ('id', models.BigAutoField(db_column='contract_id', primary_key=True, serialize=False)),
                ('scope_of_work', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimated_completion_days', models.IntegerField(blank=True, null=True)),
                ('total_contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_terms_upfront', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_terms_completion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_terms_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warranty_period', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('signed', 'Signed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installation_contract', to='services.serviceticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolarProjectProfile',
            fields=[
                ('id', models.BigAutoField(db_column='project_profile_id', primary_key=True, serialize=False)),
                ('system_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('panel_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_panels', models.IntegerField(blank=True, null=True)),
                ('inverter_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_inverters', models.IntegerField(blank=True, null=True)),
                ('battery_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('mounting_structure', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solar_project_profile', to='services.servicelocation')),
                ('original_ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_profile', to='services.serviceticket')),
            ],
        ),
        migrations.CreateModel(
            name='FieldServiceReport',
            fields=[
                ('id', models.BigAutoField(db_column='fsr_id', primary_key=True, serialize=False)),
                ('indoor_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('outdoor_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('ampere_reading', models.CharField(blank=True, max_length=50, null=True)),
                ('voltage_reading', models.CharField(blank=True, max_length=50, null=True)),
                ('before_service_readings', models.TextField(blank=True, null=True)),
                ('after_service_readings', models.TextField(blank=True, null=True)),
                ('brand_model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('client_acknowledged', models.BooleanField(default=False)),
                ('client_signature_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_service_reports', to='services.serviceticket')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalDataSheet',
            fields=[
                ('id', models.BigAutoField(db_column='tds_id', primary_key=True, serialize=False)),
                ('premise_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ownership_type', models.CharField(blank=True, max_length=100, null=True)),
                ('brownout_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose_of_going_solar', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_data_sheet', to='services.serviceticket')),
                ('ac_phase', models.CharField(blank=True, max_length=50, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('client_confirmation', models.BooleanField(default=False)),
                ('electric_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('load_schedule', models.JSONField(blank=True, default=list)),
                ('monthly_bill', models.CharField(blank=True, max_length=100, null=True)),
                ('roof_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ac_phase_power_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('attachments_json', models.JSONField(blank=True, default=dict)),
                ('average_monthly_electric_bill', models.CharField(blank=True, max_length=100, null=True)),
                ('client_confirmation_date', models.DateField(blank=True, null=True)),
                ('client_confirmed_name', models.CharField(blank=True, max_length=255, null=True)),
                ('electricity_required_hours_per_day', models.CharField(blank=True, max_length=100, null=True)),
                ('generator_details_json', models.JSONField(blank=True, default=dict)),
                ('load_schedule_json', models.JSONField(blank=True, default=list)),
                ('premise_category', models.CharField(blank=True, max_length=100, null=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_tds', to=settings.AUTH_USER_MODEL)),
                ('primary_electric_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('private_or_government_type', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tds', to=settings.AUTH_USER_MODEL)),
                ('rooftop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('solar_panel_installation_location', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RunPython(
            code=copy_technical_data_sheet_fields,
            reverse_code=reverse_copy_technical_data_sheet_fields,
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='ac_phase',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='client_confirmation',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='electric_supply',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='load_schedule',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='monthly_bill',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='roof_type',
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='data_json',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=dict, structure='dict'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='source_snapshot_json',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=dict, structure='dict'),
        ),
        migrations.AlterField(
            model_name='inspectionchecklist',
            name='checklist_items',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
        migrations.AlterField(
            model_name='inspectionchecklist',
            name='proof_media',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
        migrations.AlterField(
            model_name='inspectionchecklist',
            name='required_equipment_snapshot',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
        migrations.AlterField(
            model_name='quotationrecord',
            name='bill_of_materials',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
        migrations.AlterField(
            model_name='serviceanalytics',
            name='popular_locations',
            field=afn_service_management.fields.StructuredTextField(default=list, structure='list'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='completion_proof_images',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, help_text='List of image URLs uploaded as proof of job completion', structure='list'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='project_details',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=dict, structure='dict'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='route_geometry',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=dict, null=True, structure='dict'),
        ),
        migrations.AlterField(
            model_name='servicetrend',
            name='confidence_interval',
            field=afn_service_management.fields.StructuredTextField(default=dict, structure='dict'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='procedures',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, help_text="Ordered list of procedure steps, e.g. [{'step': 1, 'title': '...', 'description': '...'}]", structure='list'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='required_equipment',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, help_text="List of required tools/equipment, e.g. [{'name': 'Drill', 'quantity': 1}]", structure='list'),
        ),
        migrations.AlterField(
            model_name='solarcommissioningchecklist',
            name='checklist_items_json',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
        migrations.AlterField(
            model_name='solarcommissioningchecklist',
            name='readings_json',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=dict, structure='dict'),
        ),
        migrations.AlterField(
            model_name='technicaldatasheet',
            name='attachments_json',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=dict, structure='dict'),
        ),
        migrations.AlterField(
            model_name='technicaldatasheet',
            name='generator_details_json',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=dict, structure='dict'),
        ),
        migrations.AlterField(
            model_name='technicaldatasheet',
            name='load_schedule_json',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
        migrations.AlterField(
            model_name='technicaldatasheet',
            name='purpose_of_going_solar',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
    ]
