# Generated by Django 6.0.3 on 2026-06-15 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_service_ticket_inspection_workflow_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='serviceticket',
            name='services_se_assigne_9052a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceticket',
            name='services_se_assigne_55e7bc_idx',
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['superadmin', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aftersalescase',
            name='id',
            field=models.BigAutoField(db_column='after_sales_case_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='id',
            field=models.BigAutoField(db_column='demand_forecast_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inspectionchecklist',
            name='id',
            field=models.BigAutoField(db_column='inspection_checklist_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='id',
            field=models.BigAutoField(db_column='maintenance_schedule_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceanalytics',
            name='id',
            field=models.BigAutoField(db_column='service_analytics_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicelocation',
            name='id',
            field=models.BigAutoField(db_column='service_location_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='id',
            field=models.BigAutoField(db_column='service_request_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicerequestservice',
            name='id',
            field=models.BigAutoField(db_column='service_request_service_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicestatushistory',
            name='id',
            field=models.BigAutoField(db_column='service_status_history_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='id',
            field=models.BigAutoField(db_column='service_ticket_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicetrend',
            name='id',
            field=models.BigAutoField(db_column='service_trend_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='id',
            field=models.BigAutoField(db_column='service_type_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='id',
            field=models.BigAutoField(db_column='sla_rule_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='technicianlocationhistory',
            name='id',
            field=models.BigAutoField(db_column='technician_location_history_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='technicianperformance',
            name='id',
            field=models.BigAutoField(db_column='technician_performance_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='technicianskill',
            name='id',
            field=models.BigAutoField(db_column='technician_skill_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticketcrewassignment',
            name='id',
            field=models.BigAutoField(db_column='ticket_crew_assignment_id', primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['supervisor_id', 'status'], name='services_se_supervi_76c7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['supervisor_id', 'created_at'], name='services_se_supervi_45028b_idx'),
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='assigned_admin',
        ),
    ]
