# Generated by Django 6.0.6 on 2026-06-22 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_servicetype_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='serviceticket',
            name='services_se_supervi_76c7e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceticket',
            name='services_se_supervi_45028b_idx',
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='assigned_admin',
            field=models.ForeignKey(limit_choices_to={'role__in': ['superadmin', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admin_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='ticket_type',
            field=models.CharField(choices=[('inspection', 'Inspection'), ('installation', 'Installation')], default='installation', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('For Inspection', 'For Inspection'), ('Inspection Completed', 'Inspection Completed'), ('Ready for Service', 'Ready for Service'), ('Awaiting Materials', 'Awaiting Materials'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=50),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['assigned_admin_id', 'status'], name='services_se_assigne_9052a0_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['assigned_admin_id', 'created_at'], name='services_se_assigne_55e7bc_idx'),
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='supervisor',
        ),
    ]
