# Generated by Django 6.0.6 on 2026-06-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_remove_serviceticket_services_se_supervi_76c7e4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slarule',
            name='key',
            field=models.CharField(choices=[('approval_delay', 'Approval delay'), ('assignment_delay', 'Assignment delay'), ('start_delay', 'Start delay'), ('execution_delay', 'Execution delay'), ('reschedule_delay', 'Reschedule delay'), ('inspection_delay', 'Inspection delay'), ('service_ready_delay', 'Service ready delay')], max_length=40, unique=True),
        ),
    ]
