# Generated by Django 6.0.6 on 2026-06-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_arrival_validation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='arrivalvalidationlog',
            name='services_ar_ticket__286470_idx',
        ),
        migrations.RemoveIndex(
            model_name='arrivalvalidationlog',
            name='services_ar_technic_de004e_idx',
        ),
        migrations.RemoveIndex(
            model_name='arrivalvalidationlog',
            name='services_ar_action_c6d1a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='arrivalvalidationlog',
            name='services_ar_validat_308646_idx',
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('For Inspection', 'For Inspection'), ('Inspection Completed', 'Inspection Completed'), ('Ready for Service', 'Ready for Service'), ('Awaiting Materials', 'Awaiting Materials'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=50),
        ),
        migrations.DeleteModel(
            name='ArrivalValidationLog',
        ),
    ]
