# Generated by Django 5.2.8 on 2026-06-25 15:24

from django.db import migrations, models


INDEX_RENAMES = [
    (
        'services_arrival_ticket_idx',
        'services_ar_ticket__286470_idx',
        ['ticket', '-created_at'],
    ),
    (
        'services_arrival_tech_idx',
        'services_ar_technic_de004e_idx',
        ['technician', '-created_at'],
    ),
    (
        'services_arrival_action_idx',
        'services_ar_action_c6d1a7_idx',
        ['action', '-created_at'],
    ),
    (
        'services_arrival_result_idx',
        'services_ar_validat_308646_idx',
        ['validation_result', '-created_at'],
    ),
]


def _sync_indexes(apps, schema_editor, *, forward):
    ArrivalValidationLog = apps.get_model('services', 'ArrivalValidationLog')
    table_name = ArrivalValidationLog._meta.db_table
    constraints = schema_editor.connection.introspection.get_constraints(
        schema_editor.connection.cursor(),
        table_name,
    )

    for old_name, new_name, fields in INDEX_RENAMES:
        source_name = old_name if forward else new_name
        target_name = new_name if forward else old_name
        current_constraints = constraints.keys()

        if target_name in current_constraints:
            continue

        if source_name in current_constraints:
            schema_editor.remove_index(
                ArrivalValidationLog,
                models.Index(fields=fields, name=source_name),
            )

        schema_editor.add_index(
            ArrivalValidationLog,
            models.Index(fields=fields, name=target_name),
        )
        constraints = schema_editor.connection.introspection.get_constraints(
            schema_editor.connection.cursor(),
            table_name,
        )


def rename_indexes_forward(apps, schema_editor):
    _sync_indexes(apps, schema_editor, forward=True)


def rename_indexes_backward(apps, schema_editor):
    _sync_indexes(apps, schema_editor, forward=False)


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_restore_arrival_validation_workflow'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rename_indexes_forward, rename_indexes_backward),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='arrivalvalidationlog',
                    new_name='services_ar_ticket__286470_idx',
                    old_name='services_arrival_ticket_idx',
                ),
                migrations.RenameIndex(
                    model_name='arrivalvalidationlog',
                    new_name='services_ar_technic_de004e_idx',
                    old_name='services_arrival_tech_idx',
                ),
                migrations.RenameIndex(
                    model_name='arrivalvalidationlog',
                    new_name='services_ar_action_c6d1a7_idx',
                    old_name='services_arrival_action_idx',
                ),
                migrations.RenameIndex(
                    model_name='arrivalvalidationlog',
                    new_name='services_ar_validat_308646_idx',
                    old_name='services_arrival_result_idx',
                ),
            ],
        ),
    ]
