# Generated by Django 5.2.8 on 2026-06-26 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_rename_services_arrival_ticket_idx_services_ar_ticket__286470_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarCommissioningChecklist',
            fields=[
                ('id', models.BigAutoField(db_column='solar_commissioning_checklist_id', primary_key=True, serialize=False)),
                ('site_name', models.CharField(blank=True, default='', max_length=255)),
                ('inverter_type', models.CharField(blank=True, default='', max_length=255)),
                ('system_designation', models.CharField(blank=True, default='', max_length=255)),
                ('inverter_serial_number', models.CharField(blank=True, default='', max_length=255)),
                ('commissioned_date', models.DateField(blank=True, null=True)),
                ('irradiance', models.CharField(blank=True, default='', max_length=100)),
                ('ambient_temperature', models.CharField(blank=True, default='', max_length=100)),
                ('readings_json', models.JSONField(blank=True, default=dict)),
                ('checklist_items_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_solar_commissioning_checklists', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solar_commissioning_checklist', to='services.serviceticket')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['status', 'commissioned_date'], name='services_so_status_b234c3_idx')],
            },
        ),
    ]
