# Generated by Django 6.0.6 on 2026-06-27 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_solarcommissioningchecklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(db_column='generated_document_id', primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('field_service_report', 'Field Service Report'), ('turnover_acceptance', 'Turnover / Acceptance Form'), ('commissioning_checklist', 'PV Solar Site Commissioning Checklist'), ('technical_data_sheet', 'TDS - Technical Data Sheet'), ('installation_contract', 'Solar Installation Contract'), ('quotation_proposal', 'Quotation Proposal')], max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=32)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('source_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_service_documents', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='services.serviceticket')),
            ],
            options={
                'ordering': ['document_type'],
                'indexes': [models.Index(fields=['ticket', 'document_type'], name='services_ge_ticket__10c087_idx'), models.Index(fields=['document_type', '-updated_at'], name='services_ge_documen_e0fbd5_idx')],
                'constraints': [models.UniqueConstraint(fields=('ticket', 'document_type'), name='services_generated_document_unique_ticket_type')],
            },
        ),
    ]
