# Generated by Django 6.0.6 on 2026-06-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_generateddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='project_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
