# Generated by Django 6.0.6 on 2026-06-28 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_serviceticket_project_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledEquipment',
            fields=[
                ('id', models.BigAutoField(db_column='installed_equipment_id', primary_key=True, serialize=False)),
                ('brand_model', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='installed_systems', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_equipment', to='services.serviceticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
