# Generated by Django 6.0.6 on 2026-06-28 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_installedequipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationRecord',
            fields=[
                ('id', models.BigAutoField(db_column='quotation_id', primary_key=True, serialize=False)),
                ('total_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('downpayment_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('balance_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('validity_days', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('bill_of_materials', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='services.serviceticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
