# Generated by Django 6.0.6 on 2026-06-28 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_turnoveracceptance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalDataSheet',
            fields=[
                ('id', models.BigAutoField(db_column='tds_id', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('premise_type', models.CharField(blank=True, max_length=100, null=True)),
                ('premise_category', models.CharField(blank=True, max_length=100, null=True)),
                ('ownership_type', models.CharField(blank=True, max_length=100, null=True)),
                ('private_or_government_type', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_electric_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('ac_phase_power_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('solar_panel_installation_location', models.CharField(blank=True, max_length=100, null=True)),
                ('rooftop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('average_monthly_electric_bill', models.CharField(blank=True, max_length=100, null=True)),
                ('electricity_required_hours_per_day', models.CharField(blank=True, max_length=100, null=True)),
                ('brownout_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose_of_going_solar', models.CharField(blank=True, max_length=255, null=True)),
                ('load_schedule_json', models.JSONField(blank=True, default=list)),
                ('generator_details_json', models.JSONField(blank=True, default=dict)),
                ('attachments_json', models.JSONField(blank=True, default=dict)),
                ('client_confirmation_date', models.DateField(blank=True, null=True)),
                ('client_confirmed_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_tds', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tds', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_data_sheet', to='services.serviceticket')),
            ],
        ),
    ]
