# Generated by Django 6.0.6 on 2026-06-28 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0044_technicaldatasheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationContract',
            fields=[
                ('id', models.BigAutoField(db_column='contract_id', primary_key=True, serialize=False)),
                ('scope_of_work', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimated_completion_days', models.IntegerField(blank=True, null=True)),
                ('total_contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_terms_upfront', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_terms_completion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_terms_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warranty_period', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('signed', 'Signed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installation_contract', to='services.serviceticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
