# Generated by Django 6.0.6 on 2026-06-28 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0045_installationcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldServiceReport',
            fields=[
                ('id', models.BigAutoField(db_column='fsr_id', primary_key=True, serialize=False)),
                ('indoor_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('outdoor_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('ampere_reading', models.CharField(blank=True, max_length=50, null=True)),
                ('voltage_reading', models.CharField(blank=True, max_length=50, null=True)),
                ('before_service_readings', models.TextField(blank=True, null=True)),
                ('after_service_readings', models.TextField(blank=True, null=True)),
                ('brand_model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('client_acknowledged', models.BooleanField(default=False)),
                ('client_signature_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_service_report', to='services.serviceticket')),
            ],
        ),
        migrations.CreateModel(
            name='SolarProjectProfile',
            fields=[
                ('id', models.BigAutoField(db_column='project_profile_id', primary_key=True, serialize=False)),
                ('system_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('panel_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_panels', models.IntegerField(blank=True, null=True)),
                ('inverter_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_inverters', models.IntegerField(blank=True, null=True)),
                ('battery_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('mounting_structure', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solar_project_profile', to='services.servicelocation')),
                ('original_ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_profile', to='services.serviceticket')),
            ],
        ),
    ]
