# Generated by Django 6.0.6 on 2026-06-28 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0046_fieldservicereport_solarprojectprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='ac_phase_power_supply',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='attachments_json',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='average_monthly_electric_bill',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='client_confirmation_date',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='client_confirmed_name',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='electricity_required_hours_per_day',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='generator_details_json',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='load_schedule_json',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='premise_category',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='prepared_by',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='primary_electric_supply',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='private_or_government_type',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='rooftop_type',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='solar_panel_installation_location',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='status',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='ac_phase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='client_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='electric_supply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='load_schedule',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='monthly_bill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='roof_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fieldservicereport',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_service_reports', to='services.serviceticket'),
        ),
        migrations.AlterField(
            model_name='technicaldatasheet',
            name='purpose_of_going_solar',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
