# Generated by Django 6.0.6 on 2026-06-30 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_technical_data_sheet_fields(apps, schema_editor):
    TechnicalDataSheet = apps.get_model('services', 'TechnicalDataSheet')

    for record in TechnicalDataSheet.objects.all():
        record.ac_phase_power_supply = record.ac_phase or record.ac_phase_power_supply
        record.attachments_json = (
            {'items': record.attachments}
            if isinstance(record.attachments, list) and record.attachments
            else (record.attachments_json or {})
        )
        record.average_monthly_electric_bill = record.monthly_bill or record.average_monthly_electric_bill
        record.primary_electric_supply = record.electric_supply or record.primary_electric_supply
        record.load_schedule_json = record.load_schedule or record.load_schedule_json
        record.rooftop_type = record.roof_type or record.rooftop_type

        update_fields = [
            'ac_phase_power_supply',
            'attachments_json',
            'average_monthly_electric_bill',
            'primary_electric_supply',
            'load_schedule_json',
            'rooftop_type',
        ]
        record.save(update_fields=update_fields)


def reverse_copy_technical_data_sheet_fields(apps, schema_editor):
    TechnicalDataSheet = apps.get_model('services', 'TechnicalDataSheet')

    for record in TechnicalDataSheet.objects.all():
        record.ac_phase = record.ac_phase_power_supply or record.ac_phase
        attachments = record.attachments_json or {}
        if isinstance(attachments, dict):
            record.attachments = attachments.get('items') or []
        elif isinstance(attachments, list):
            record.attachments = attachments
        record.monthly_bill = record.average_monthly_electric_bill or record.monthly_bill
        record.electric_supply = record.primary_electric_supply or record.electric_supply
        record.load_schedule = record.load_schedule_json or record.load_schedule
        record.roof_type = record.rooftop_type or record.roof_type

        update_fields = [
            'ac_phase',
            'attachments',
            'monthly_bill',
            'electric_supply',
            'load_schedule',
            'roof_type',
        ]
        record.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0047_remove_technicaldatasheet_ac_phase_power_supply_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technicaldatasheet',
            name='ac_phase_power_supply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='attachments_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='average_monthly_electric_bill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='client_confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='client_confirmed_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='electricity_required_hours_per_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='generator_details_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='load_schedule_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='premise_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_tds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='primary_electric_supply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='private_or_government_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='rooftop_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='solar_panel_installation_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(copy_technical_data_sheet_fields, reverse_copy_technical_data_sheet_fields),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='ac_phase',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='client_confirmation',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='electric_supply',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='load_schedule',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='monthly_bill',
        ),
        migrations.RemoveField(
            model_name='technicaldatasheet',
            name='roof_type',
        ),
    ]
