# Generated by Django 6.0.6 on 2026-07-01 04:05

import afn_service_management.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0048_restore_canonical_technicaldatasheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='data_json',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=dict, structure='dict'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='source_snapshot_json',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=dict, structure='dict'),
        ),
        migrations.AlterField(
            model_name='inspectionchecklist',
            name='checklist_items',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
        migrations.AlterField(
            model_name='inspectionchecklist',
            name='proof_media',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
        migrations.AlterField(
            model_name='inspectionchecklist',
            name='required_equipment_snapshot',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
        migrations.AlterField(
            model_name='quotationrecord',
            name='bill_of_materials',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
        migrations.AlterField(
            model_name='serviceanalytics',
            name='popular_locations',
            field=afn_service_management.fields.StructuredTextField(default=list, structure='list'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='completion_proof_images',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, help_text='List of image URLs uploaded as proof of job completion', structure='list'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='project_details',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=dict, structure='dict'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='route_geometry',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=dict, null=True, structure='dict'),
        ),
        migrations.AlterField(
            model_name='servicetrend',
            name='confidence_interval',
            field=afn_service_management.fields.StructuredTextField(default=dict, structure='dict'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='procedures',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, help_text="Ordered list of procedure steps, e.g. [{'step': 1, 'title': '...', 'description': '...'}]", structure='list'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='required_equipment',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, help_text="List of required tools/equipment, e.g. [{'name': 'Drill', 'quantity': 1}]", structure='list'),
        ),
        migrations.AlterField(
            model_name='solarcommissioningchecklist',
            name='checklist_items_json',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
        migrations.AlterField(
            model_name='solarcommissioningchecklist',
            name='readings_json',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=dict, structure='dict'),
        ),
        migrations.AlterField(
            model_name='technicaldatasheet',
            name='attachments_json',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=dict, structure='dict'),
        ),
        migrations.AlterField(
            model_name='technicaldatasheet',
            name='generator_details_json',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=dict, structure='dict'),
        ),
        migrations.AlterField(
            model_name='technicaldatasheet',
            name='load_schedule_json',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
        migrations.AlterField(
            model_name='technicaldatasheet',
            name='purpose_of_going_solar',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
    ]
