# Generated by Django 6.0.6 on 2026-07-13 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0050_servicetype_requires_site_inspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarEstimate',
            fields=[
                ('id', models.BigAutoField(db_column='solar_estimate_id', primary_key=True, serialize=False)),
                ('calculation_mode', models.CharField(choices=[('monthly', 'Monthly consumption'), ('appliances', 'Appliance load schedule')], default='monthly', max_length=20)),
                ('monthly_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('appliances', models.JSONField(blank=True, default=list)),
                ('peak_sun_hours', models.DecimalField(decimal_places=2, default=5, max_digits=4)),
                ('system_loss_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('panel_wattage', models.PositiveIntegerField(default=550)),
                ('electricity_rate', models.DecimalField(decimal_places=2, default=12, max_digits=8)),
                ('desired_offset_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('available_roof_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selected_promotion', models.JSONField(blank=True, default=dict)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('calculation_version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('reviewed', 'Reviewed'), ('converted', 'Converted to service request'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='solar_estimates', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solar_estimate', to='services.servicerequest')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['client', 'status'], name='services_so_client__707c44_idx'), models.Index(fields=['status', 'created_at'], name='services_so_status_8bac83_idx')],
            },
        ),
    ]
