# Generated by Django 6.0.3 on 2026-06-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprogress',
            name='id',
            field=models.BigAutoField(db_column='ticket_progress_id', primary_key=True, serialize=False),
        ),
    ]
