# Generated by Django 6.0.5 on 2026-06-10 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0003_staff_chat_rooms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupportCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_key', models.CharField(max_length=80, unique=True)),
                ('subject', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('billing', 'Billing Concern'), ('schedule', 'Schedule Concern'), ('technical', 'Technical Help'), ('complaint', 'Complaint'), ('warranty', 'Warranty Question')], default='general', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_support_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['client', '-updated_at'], name='messages_ap_client__636623_idx'), models.Index(fields=['status', '-updated_at'], name='messages_ap_status_af29c0_idx'), models.Index(fields=['priority', '-updated_at'], name='messages_ap_priorit_9dc908_idx')],
            },
        ),
    ]
