# Generated by Django 6.0.3 on 2026-06-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0004_customersupportcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupportcase',
            name='id',
            field=models.BigAutoField(db_column='customer_support_case_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(db_column='message_id', primary_key=True, serialize=False),
        ),
    ]
