# Generated by Django 6.0.6 on 2026-06-28 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0006_message_edit_delete_image'),
        ('services', '0045_installationcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupportcase',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cases', to='services.serviceticket'),
        ),
    ]
