# Generated by Django 6.0.3 on 2026-06-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_servicetypeinventoryrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycategory',
            name='id',
            field=models.BigAutoField(db_column='inventory_category_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='id',
            field=models.BigAutoField(db_column='inventory_item_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventoryreservation',
            name='id',
            field=models.BigAutoField(db_column='inventory_reservation_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='id',
            field=models.BigAutoField(db_column='inventory_transaction_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicetypeinventoryrequirement',
            name='id',
            field=models.BigAutoField(db_column='service_type_inventory_requirement_id', primary_key=True, serialize=False),
        ),
    ]
