"""
Django settings for afn_service_management project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import logging
import sys
import tempfile
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

_settings_logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR.parent / '.env')


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None or value == '':
        return default
    return value.lower() in ('true', '1', 'yes', 'on')


def env_list(name, default=''):
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


def env_int(name, default, *, minimum=None, maximum=None):
    raw_value = os.environ.get(name, str(default)).strip()
    try:
        value = int(raw_value)
    except ValueError as exc:
        raise ImproperlyConfigured(f'{name} must be a whole number.') from exc
    if minimum is not None and value < minimum:
        raise ImproperlyConfigured(f'{name} must be at least {minimum}.')
    if maximum is not None and value > maximum:
        raise ImproperlyConfigured(f'{name} must be at most {maximum}.')
    return value


def env_float(name, default, *, minimum=None, maximum=None):
    raw_value = os.environ.get(name, str(default)).strip()
    try:
        value = float(raw_value)
    except ValueError as exc:
        raise ImproperlyConfigured(f'{name} must be a number.') from exc
    if minimum is not None and value < minimum:
        raise ImproperlyConfigured(f'{name} must be at least {minimum}.')
    if maximum is not None and value > maximum:
        raise ImproperlyConfigured(f'{name} must be at most {maximum}.')
    return value


def build_postgres_config_from_url(database_url):
    """
    Build Django PostgreSQL settings from a standard DATABASE_URL.

    This supports hosted services such as Aiven, which usually provide a
    postgres:// or postgresql:// connection string with sslmode=require.
    """
    parsed = urlparse(database_url)
    if parsed.scheme not in ('postgres', 'postgresql'):
        raise ValueError(f'Unsupported database URL scheme: {parsed.scheme}')

    query_params = parse_qs(parsed.query)
    options = {
        'connect_timeout': int(os.environ.get('DB_CONNECT_TIMEOUT', '10')),
    }

    sslmode = os.environ.get('DB_SSLMODE')
    if not sslmode and query_params.get('sslmode'):
        sslmode = query_params['sslmode'][0]
    if not sslmode:
        sslmode = 'require'
    options['sslmode'] = sslmode

    # Keep the service hostname for PostgreSQL while allowing the local dev
    # launcher to pin a reachable address behind a rotating DNS endpoint.
    hostaddr = os.environ.get('DB_HOSTADDR', '').strip()
    if hostaddr:
        options['hostaddr'] = hostaddr

    sslrootcert = os.environ.get('DB_SSLROOTCERT', '').strip()
    if sslrootcert:
        options['sslrootcert'] = sslrootcert

    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or 5432),
        'OPTIONS': options,
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
    }

# SECURITY WARNING: don't run with debug turned on in production!
ENVIRONMENT = os.environ.get('DJANGO_ENV', 'development').lower()
IS_PRODUCTION = ENVIRONMENT == 'production'
DEPLOYMENT_STAGE = os.environ.get('DEPLOYMENT_STAGE', ENVIRONMENT).lower()
DEBUG = env_bool('DEBUG', default=ENVIRONMENT == 'development')
IS_TEST = 'test' in sys.argv

# Channels/ASGI: /static/ must be wired in urlpatterns (see urls.py). Django's helper only
# attaches when DEBUG=True; if DEBUG is False locally/Docker, admin CSS/JS return HTML 404.
# Never enable in production (use nginx or WhiteNoise + collectstatic instead).
SERVE_STATIC_URLPATTERNS = (not IS_PRODUCTION) and env_bool('DJANGO_SERVE_STATIC', default=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Generate a temporary key for development only
        import secrets
        SECRET_KEY = secrets.token_urlsafe(50)
    else:
        raise ValueError('SECRET_KEY environment variable must be set in production')

DEFAULT_ALLOWED_HOSTS = 'localhost,127.0.0.1,testserver' if DEBUG else ''
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', DEFAULT_ALLOWED_HOSTS)

# OpenRouteService API key support (for route geometry and ETA)
OPENROUTESERVICE_API_KEY = os.environ.get('OPENROUTESERVICE_API_KEY', '').strip()
ORS_API_KEY = os.environ.get('ORS_API_KEY', OPENROUTESERVICE_API_KEY).strip()

# Field-location contract. Bounds are returned by the authenticated tracking APIs
# so deployed frontends do not need a region hard-coded into their build.
TRACKING_REGION_NAME = os.environ.get('TRACKING_REGION_NAME', 'CALABARZON').strip() or 'Service region'
TRACKING_REGION_SOUTH_LAT = env_float('TRACKING_REGION_SOUTH_LAT', 13.38, minimum=-90, maximum=90)
TRACKING_REGION_WEST_LNG = env_float('TRACKING_REGION_WEST_LNG', 119.88, minimum=-180, maximum=180)
TRACKING_REGION_NORTH_LAT = env_float('TRACKING_REGION_NORTH_LAT', 14.96, minimum=-90, maximum=90)
TRACKING_REGION_EAST_LNG = env_float('TRACKING_REGION_EAST_LNG', 122.42, minimum=-180, maximum=180)
TRACKING_REGION_MIN_ZOOM = env_int('TRACKING_REGION_MIN_ZOOM', 8, minimum=1, maximum=18)
TECHNICIAN_LOCATION_RETENTION_DAYS = env_int(
    'TECHNICIAN_LOCATION_RETENTION_DAYS', 30, minimum=1, maximum=3650
)
TECHNICIAN_LOCATION_TRAIL_MINUTES = env_int(
    'TECHNICIAN_LOCATION_TRAIL_MINUTES', 60, minimum=5, maximum=480
)
if TRACKING_REGION_SOUTH_LAT >= TRACKING_REGION_NORTH_LAT:
    raise ImproperlyConfigured('TRACKING_REGION_SOUTH_LAT must be below TRACKING_REGION_NORTH_LAT.')
if TRACKING_REGION_WEST_LNG >= TRACKING_REGION_EAST_LNG:
    raise ImproperlyConfigured('TRACKING_REGION_WEST_LNG must be west of TRACKING_REGION_EAST_LNG.')



# Security Settings
ENABLE_HTTPS = env_bool('ENABLE_HTTPS', default=IS_PRODUCTION and not IS_TEST)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=ENABLE_HTTPS)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', default=ENABLE_HTTPS)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', default=ENABLE_HTTPS)
USE_X_FORWARDED_HOST = env_bool('USE_X_FORWARDED_HOST', default=IS_PRODUCTION)
SECURE_PROXY_SSL_HEADER = (
    ('HTTP_X_FORWARDED_PROTO', 'https')
    if env_bool('USE_X_FORWARDED_PROTO', default=IS_PRODUCTION)
    else None
)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000' if SECURE_SSL_REDIRECT else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=SECURE_SSL_REDIRECT)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', default=False)

# Rate limiting (basic - install django-ratelimit for advanced)
# LOGIN_URL removed - using API authentication instead of template auth
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Application definition

INSTALLED_APPS = [
    # Daphne must be first (before staticfiles)
    'daphne',

    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'channels',
    'cloudinary',
    'cloudinary_storage',

    # Custom apps
    'users',
    'services',
    'progress',
    'messages_app',
    'notifications',
    'history',
    'inventory',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'users.middleware.ChangeLogUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'afn_service_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'afn_service_management.wsgi.application'

# ASGI application for Channels
# ASGI_APPLICATION = 'afn_service_management.asgi.application'

# Channel layers for WebSocket support (use in-memory for development)
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer',
#     },
# }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database configuration with environment variable support
DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()
DATABASE_ENGINE = os.environ.get('DATABASE_ENGINE', 'sqlite3').lower()
USE_STAGING_TEST_DATABASE = IS_TEST and env_bool('USE_STAGING_TEST_DATABASE', default=False)

if USE_STAGING_TEST_DATABASE:
    staging_test_database_url = os.environ.get('STAGING_TEST_DATABASE_URL', '').strip()
    staging_test_database_name = os.environ.get('STAGING_TEST_DATABASE_NAME', '').strip()
    staging_confirmation = os.environ.get('STAGING_TEST_CONFIRM_DISPOSABLE', '').strip().lower()
    if staging_confirmation != 'disposable-staging':
        raise ImproperlyConfigured(
            'Set STAGING_TEST_CONFIRM_DISPOSABLE=disposable-staging before using the staging test database.'
        )
    if not staging_test_database_url:
        raise ImproperlyConfigured('STAGING_TEST_DATABASE_URL is required for staging database tests.')
    if not staging_test_database_name.lower().startswith('test_'):
        raise ImproperlyConfigured('STAGING_TEST_DATABASE_NAME must start with test_.')

    staging_database_config = build_postgres_config_from_url(staging_test_database_url)
    if staging_test_database_name == staging_database_config['NAME']:
        raise ImproperlyConfigured('The staging test database must differ from the connection database.')
    staging_database_config['TEST'] = {'NAME': staging_test_database_name}
    DATABASES = {'default': staging_database_config}
    _settings_logger.info('Using the explicitly confirmed disposable PostgreSQL staging test database')
elif IS_TEST:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    _settings_logger.info("Using SQLite database for testing")
elif DATABASE_URL:
    DATABASES = {
        'default': build_postgres_config_from_url(DATABASE_URL),
    }
    _settings_logger.info('Using PostgreSQL database from DATABASE_URL')
elif DATABASE_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'afn_service_db'),
            'USER': os.environ.get('DB_USER', 'afn_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'your_secure_password'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                'connect_timeout': int(os.environ.get('DB_CONNECT_TIMEOUT', '10')),
                'sslmode': os.environ.get('DB_SSLMODE', 'prefer'),
                **(
                    {'sslrootcert': os.environ['DB_SSLROOTCERT'].strip()}
                    if os.environ.get('DB_SSLROOTCERT', '').strip()
                    else {}
                ),
            },
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        }
    }
    _settings_logger.info('Using PostgreSQL database from DB_* env vars')
elif DATABASE_ENGINE == 'sqlite3':
    # Default to SQLite for development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / os.environ.get('SQLITE_DB_PATH', 'db.sqlite3'),
            'OPTIONS': {
                'timeout': 20,
            }
        }
    }
    _settings_logger.info("Using SQLite database")
else:
    raise ValueError(
        f"Unsupported DATABASE_ENGINE: {DATABASE_ENGINE}. Use 'sqlite3', 'postgresql', or set DATABASE_URL."
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

if IS_TEST:
    PASSWORD_HASHERS = [
        'afn_service_management.hashers.FastTestPBKDF2PasswordHasher',
    ]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('TIME_ZONE', 'UTC')
BUSINESS_DISPLAY_TIMEZONE = os.environ.get('BUSINESS_DISPLAY_TIMEZONE', 'Asia/Singapore')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Must be root-relative so {% static %} URLs work under nested paths (e.g. /admin/login/).
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # include custom static directory
STATIC_ROOT = Path(os.environ.get('STATIC_ROOT', str(BASE_DIR / 'staticfiles')))
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CLOUDINARY_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME', '').strip()
CLOUDINARY_API_KEY = os.environ.get('CLOUDINARY_API_KEY', '').strip()
CLOUDINARY_API_SECRET = os.environ.get('CLOUDINARY_API_SECRET', '').strip()
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
    'API_KEY': CLOUDINARY_API_KEY,
    'API_SECRET': CLOUDINARY_API_SECRET,
}
USE_CLOUDINARY_MEDIA = (
    not IS_TEST
    and all([CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET])
)
MEDIA_STORAGE_BACKEND = (
    'cloudinary_storage.storage.MediaCloudinaryStorage'
    if USE_CLOUDINARY_MEDIA
    else 'django.core.files.storage.FileSystemStorage'
)

STORAGES = {
    'default': {
        'BACKEND': MEDIA_STORAGE_BACKEND,
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = (
    Path(tempfile.gettempdir()) / 'afn-service-management-test-media'
    if IS_TEST
    else BASE_DIR / 'media'
)

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'afn_service_management.exceptions.api_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_RENDERER_CLASSES': (
        [
            'rest_framework.renderers.JSONRenderer',
            'rest_framework.renderers.BrowsableAPIRenderer',
        ] if DEBUG else [
            'rest_framework.renderers.JSONRenderer',
        ]
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/minute' if DEBUG else '5/minute',
        'register': '5/hour',
        'password_reset': '5/minute',
        'service_request_create': '5/hour',
        'message_send': '20/minute',
        'notification_action': '60/minute',
        'geocode': '30/minute',
        'route_api': '20/minute',
    },
}

# CORS settings for React frontend — restrict origins in production!
# CORS_ALLOW_ALL_ORIGINS = False  # Uncomment and set CORS_ALLOWED_ORIGINS in production
DEFAULT_FRONTEND_ORIGINS = (
    'http://localhost:5173,'
    'http://127.0.0.1:5173,'
    'http://localhost:5174,'
    'http://127.0.0.1:5174,'
    'http://localhost:3000,'
    'http://127.0.0.1:3000'
    if DEBUG else ''
)
CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', default=False)
CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS', DEFAULT_FRONTEND_ORIGINS)
CORS_ALLOWED_ORIGIN_REGEXES = (
    [
        r"^http://localhost:\d+$",
        r"^http://127\.0\.0\.1:\d+$",
    ] if DEBUG else []
)
CORS_ALLOW_CREDENTIALS = env_bool('CORS_ALLOW_CREDENTIALS', default=True)
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS', DEFAULT_FRONTEND_ORIGINS)
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL') or (
    CORS_ALLOWED_ORIGINS[0] if CORS_ALLOWED_ORIGINS else 'http://localhost:5173'
)
EMAIL_VERIFICATION_EXPIRY_HOURS = int(os.environ.get('EMAIL_VERIFICATION_EXPIRY_HOURS', '24'))
EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS = int(
    os.environ.get('EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS', '60')
)

# Email settings (configure for your email provider)
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL') or os.environ.get('EMAIL_HOST_USER') or 'AFN Service <noreply@afnservice.com>'

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# API Keys and Free External Services Configuration
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY')

OPENWEATHER_API_KEY = os.environ.get('OPENWEATHER_API_KEY')  # optional free service


# Admin phone numbers for SMS alerts (comma-separated)
ADMIN_PHONE_NUMBERS = os.environ.get('ADMIN_PHONE_NUMBERS', '').split(',') if os.environ.get('ADMIN_PHONE_NUMBERS') else []

# Email settings from environment
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', default=False)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Django Channels configuration for WebSocket support
ASGI_APPLICATION = 'afn_service_management.asgi.application'

USE_REDIS = env_bool('USE_REDIS', default=IS_PRODUCTION)
REDIS_URL = os.environ.get(
    'REDIS_URL',
    '' if IS_PRODUCTION else 'redis://127.0.0.1:6379/0',
).strip()

if USE_REDIS:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
                'capacity': int(os.environ.get('CHANNEL_CAPACITY', '10000')),
                'expiry': int(os.environ.get('CHANNEL_EXPIRY_SECONDS', str(10 * 60))),
            },
        }
    }
else:
    # Each process has its own isolated layer. This is suitable only for local
    # development and tests, never for a multi-process production deployment.
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }


def validate_production_settings():
    """Fail startup when a production deployment would be unsafe or lossy."""
    if not IS_PRODUCTION or IS_TEST:
        return

    errors = []
    if DEBUG:
        errors.append('DEBUG must be False')
    if len(SECRET_KEY) < 50 or SECRET_KEY.startswith(('replace-', 'your-')):
        errors.append('SECRET_KEY must be a strong, unique value of at least 50 characters')
    if not ALLOWED_HOSTS:
        errors.append('ALLOWED_HOSTS must contain the deployed backend hostname')
    if CORS_ALLOW_ALL_ORIGINS:
        errors.append('CORS_ALLOW_ALL_ORIGINS must be False')
    if not CORS_ALLOWED_ORIGINS:
        errors.append('CORS_ALLOWED_ORIGINS must contain the deployed frontend origin')
    if not CSRF_TRUSTED_ORIGINS:
        errors.append('CSRF_TRUSTED_ORIGINS must contain the deployed frontend origin')
    if not FRONTEND_BASE_URL.startswith('https://'):
        errors.append('FRONTEND_BASE_URL must use HTTPS')
    if not ENABLE_HTTPS:
        errors.append('ENABLE_HTTPS must be True')
    if DATABASES['default']['ENGINE'] != 'django.db.backends.postgresql':
        errors.append('production must use PostgreSQL via DATABASE_URL or DATABASE_ENGINE=postgresql')
    if not USE_CLOUDINARY_MEDIA and not env_bool('ALLOW_LOCAL_MEDIA_IN_PRODUCTION', default=False):
        errors.append(
            'Cloudinary credentials are required for durable production uploads '
            '(or explicitly set ALLOW_LOCAL_MEDIA_IN_PRODUCTION=True when using a persistent volume)'
        )
    if not USE_REDIS and not env_bool('ALLOW_INMEMORY_CHANNEL_LAYER_IN_PRODUCTION', default=False):
        errors.append(
            'USE_REDIS=True and REDIS_URL are required for production WebSockets '
            '(or explicitly set ALLOW_INMEMORY_CHANNEL_LAYER_IN_PRODUCTION=True for a single-process deployment)'
        )
    if USE_REDIS and not REDIS_URL:
        errors.append('REDIS_URL must be set when USE_REDIS=True')
    if EMAIL_USE_TLS and EMAIL_USE_SSL:
        errors.append('EMAIL_USE_TLS and EMAIL_USE_SSL cannot both be True')
    if EMAIL_BACKEND == 'django.core.mail.backends.smtp.EmailBackend':
        if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
            errors.append('EMAIL_HOST_USER and EMAIL_HOST_PASSWORD are required for SMTP email')

    if errors:
        formatted = '\n - '.join(errors)
        raise ImproperlyConfigured(f'Invalid production configuration:\n - {formatted}')


validate_production_settings()

if IS_TEST:
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        'anon': '100000/day',
        'user': '100000/day',
        # Keep the real development login limit so the authentication flow is
        # exercised in tests. Other high-volume scopes remain relaxed.
        'login': '10/minute',
        'register': '100000/day',
        'password_reset': '100000/day',
        'service_request_create': '100000/day',
        'message_send': '100000/day',
        'notification_action': '100000/day',
        'geocode': '100000/day',
        'route_api': '100000/day',
    }
