# Generated by Django 6.0.6 on 2026-07-01 04:11

import afn_service_management.fields
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


AFTER_SALES_CAPABILITIES = [
    'after_sales.dashboard.view',
    'after_sales.cases.view',
    'after_sales.cases.manage',
]

OPERATIONS_CAPABILITIES = [
    'supervisor.dashboard.view',
    'supervisor.tickets.view',
    'supervisor.dispatch.view',
    'supervisor.tracking.view',
    'users.capabilities.manage_staff',
]


def rename_after_sales_role(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(role='after_sales').update(role='follow_up')
    User.objects.filter(admin_scope='after_sales').update(admin_scope='service_follow_up')


def rename_follow_up_role_back(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(role='follow_up').update(role='after_sales')
    User.objects.filter(admin_scope='service_follow_up').update(admin_scope='after_sales')


def promote_bootstrap_owner(apps, schema_editor):
    User = apps.get_model('users', 'User')

    if User.objects.filter(role='superadmin').exists():
        return

    superuser_admins = User.objects.filter(role='admin', is_superuser=True).order_by('id')
    if superuser_admins.count() == 1:
        owner = superuser_admins.first()
        owner.role = 'superadmin'
        owner.save(update_fields=['role'])
        return

    admins = User.objects.filter(role='admin').order_by('id')
    if admins.count() == 1:
        owner = admins.first()
        owner.role = 'superadmin'
        owner.save(update_fields=['role'])


def demote_promoted_owner(apps, schema_editor):
    User = apps.get_model('users', 'User')
    if User.objects.filter(role='superadmin').count() == 1 and not User.objects.filter(role='admin').exists():
        owner = User.objects.filter(role='superadmin').first()
        owner.role = 'admin'
        owner.save(update_fields=['role'])


def convert_legacy_management_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    UserCapabilityGrant = apps.get_model('users', 'UserCapabilityGrant')
    ManagementProfile = apps.get_model('users', 'ManagementProfile')

    role_capability_map = {
        'follow_up': AFTER_SALES_CAPABILITIES,
        'supervisor': OPERATIONS_CAPABILITIES,
    }
    scope_map = {
        'follow_up': 'service_follow_up',
        'supervisor': 'operations',
    }

    for legacy_role, capabilities in role_capability_map.items():
        for user in User.objects.filter(role=legacy_role):
            user.role = 'admin'
            user.save(update_fields=['role'])

            ManagementProfile.objects.update_or_create(
                user=user,
                defaults={'admin_scope': scope_map[legacy_role]},
            )

            for capability_code in capabilities:
                UserCapabilityGrant.objects.get_or_create(
                    user=user,
                    capability_code=capability_code,
                    defaults={'granted_by': None},
                )


def restore_legacy_management_roles(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_auto_20260306_1911'), ('users', '0003_user_current_latitude_user_current_longitude_and_more'), ('users', '0004_user_admin_scope'), ('users', '0005_alter_user_role'), ('users', '0006_alter_user_admin_scope_alter_user_role'), ('users', '0007_adminsettings'), ('users', '0008_usercapabilitygrant'), ('users', '0009_alter_user_status'), ('users', '0010_superadmin_role'), ('users', '0011_alter_user_options_user_users_user_role_f59a08_idx_and_more'), ('users', '0012_changelog'), ('users', '0013_clientprofile_followupprofile_managementprofile_and_more'), ('users', '0014_alter_user_phone_alter_user_role'), ('users', '0015_alter_user_phone'), ('users', '0016_restore_staff_role_choices'), ('users', '0017_remove_legacy_management_roles'), ('users', '0018_activitylog'), ('users', '0019_user_email_verification'), ('users', '0020_remove_adminsettings_sms_notifications_enabled'), ('users', '0021_remove_user_email_verification_sent_at_and_more'), ('users', '0022_restore_user_email_verification'), ('users', '0023_user_profile_image'), ('users', '0024_adminsettings_overtime_dispatch'), ('users', '0025_activitylog_actor_display_name'), ('users', '0026_user_pending_email'), ('users', '0027_alter_changelog_action_alter_changelog_changed_at_and_more'), ('users', '0028_arrival_validation'), ('users', '0029_remove_adminsettings_arrival_radius_meters_and_more'), ('users', '0030_restore_arrival_validation_settings'), ('users', '0031_user_landline_user_middle_name'), ('users', '0032_alter_activitylog_metadata_and_more')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('follow_up', 'Service Follow-Up'), ('supervisor', 'Supervisor'), ('technician', 'Technician'), ('client', 'Client')], default='client', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('admin_scope', models.CharField(blank=True, choices=[('service_follow_up', 'Service Follow-Up'), ('task_management', 'Task Management'), ('operations', 'Operations Management'), ('general', 'General Administration')], default='general', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RunPython(code=rename_after_sales_role, reverse_code=rename_follow_up_role_back),
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='AFN Service Management', max_length=255)),
                ('support_email', models.EmailField(default='support@afnservice.com', max_length=254)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('auto_dispatch_enabled', models.BooleanField(default=False)),
                ('sms_notifications_enabled', models.BooleanField(default=False)),
                ('default_time_zone', models.CharField(default='UTC', max_length=100)),
                ('max_technician_assignments', models.PositiveSmallIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Settings',
                'verbose_name_plural': 'Admin Settings',
            },
        ),
        migrations.CreateModel(
            name='UserCapabilityGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability_code', models.CharField(max_length=100)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_capability_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Capability Grant',
                'verbose_name_plural': 'User Capability Grants',
                'ordering': ['capability_code', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'capability_code'), name='unique_user_capability_grant')],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('follow_up', 'Service Follow-Up'), ('supervisor', 'Supervisor'), ('technician', 'Technician'), ('client', 'Client')], default='client', max_length=20),
        ),
        migrations.RunPython(code=promote_bootstrap_owner, reverse_code=demote_promoted_owner),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_available', 'status'], name='users_user_role_f59a08_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='users_user_role_6e67fb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_user_usernam_65d164_idx'),
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='The primary key of the changed record')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], help_text='Type of change: create, update, or delete', max_length=20)),
                ('field_name', models.CharField(blank=True, default='', help_text='The specific field that changed (empty for create/delete)', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Value before the change', null=True)),
                ('new_value', models.TextField(blank=True, help_text='Value after the change', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the change occurred')),
                ('summary', models.CharField(blank=True, default='', help_text='Human-readable summary of the change', max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, help_text='The user who made this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(help_text='The model type that was changed', on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Change Log',
                'verbose_name_plural': 'Change Logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='users_chang_content_46a98d_idx'), models.Index(fields=['changed_by', 'changed_at'], name='users_chang_changed_45d8fb_idx'), models.Index(fields=['action', 'changed_at'], name='users_chang_action_95889f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('corporate', 'Corporate')], default='individual', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS')], default='email', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
            },
        ),
        migrations.CreateModel(
            name='FollowUpProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('general', 'General'), ('maintenance', 'Maintenance'), ('warranty', 'Warranty'), ('complaint', 'Complaint Resolution')], default='general', max_length=20)),
                ('max_case_load', models.PositiveSmallIntegerField(default=50)),
                ('current_case_load', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Follow-Up Profile',
                'verbose_name_plural': 'Follow-Up Profiles',
            },
        ),
        migrations.CreateModel(
            name='ManagementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_scope', models.CharField(choices=[('service_follow_up', 'Service Follow-Up'), ('task_management', 'Task Management'), ('operations', 'Operations Management'), ('general', 'General Administration')], default='general', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Management Profile',
                'verbose_name_plural': 'Management Profiles',
            },
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('field_service', 'Field Service'), ('maintenance', 'Maintenance'), ('installation', 'Installation'), ('repair', 'Repair')], default='field_service', max_length=20)),
                ('max_technicians', models.PositiveSmallIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supervisor Profile',
                'verbose_name_plural': 'Supervisor Profiles',
            },
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('preferred_work_areas', models.JSONField(blank=True, default=list)),
                ('max_daily_assignments', models.PositiveSmallIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Technician Profile',
                'verbose_name_plural': 'Technician Profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='usercapabilitygrant',
            options={'ordering': ['user', 'capability_code'], 'verbose_name': 'User Capability Grant', 'verbose_name_plural': 'User Capability Grants'},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_role_f59a08_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_settings_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('follow_up', 'Follow-Up Specialist'), ('supervisor', 'Supervisor'), ('technician', 'Technician'), ('client', 'Client')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followupprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managementprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin_scope',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_location_update',
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['client_type'], name='users_clien_client__254b09_idx'),
        ),
        migrations.AddIndex(
            model_name='followupprofile',
            index=models.Index(fields=['specialization'], name='users_follo_special_9b47f0_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisorprofile',
            index=models.Index(fields=['department'], name='users_super_departm_93729c_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['is_available'], name='users_techn_is_avai_264a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['skill_level'], name='users_techn_skill_l_4eb0b1_idx'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number (11 digits, format: +63 9XX XXX XXXX)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('follow_up', 'Service Follow-Up'), ('supervisor', 'Supervisor'), ('technician', 'Technician'), ('client', 'Client')], default='client', max_length=20),
        ),
        migrations.RunPython(
            code=convert_legacy_management_roles,
            reverse_code=restore_legacy_management_roles,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('technician', 'Technician'), ('client', 'Client')], default='client', max_length=20),
        ),
        migrations.DeleteModel(
            name='FollowUpProfile',
        ),
        migrations.DeleteModel(
            name='SupervisorProfile',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='sms_notifications_enabled',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='id',
            field=models.BigAutoField(db_column='admin_settings_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='id',
            field=models.BigAutoField(db_column='change_log_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='id',
            field=models.BigAutoField(db_column='client_profile_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='managementprofile',
            name='id',
            field=models.BigAutoField(db_column='management_profile_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='id',
            field=models.BigAutoField(db_column='technician_profile_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(db_column='user_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercapabilitygrant',
            name='id',
            field=models.BigAutoField(db_column='user_capability_grant_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='allow_overtime_dispatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='overtime_daily_capacity_minutes',
            field=models.PositiveSmallIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='field_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='arrival_radius_meters',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='location_validation_disabled_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='location_validation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='location_validation_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='location_validation_updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_validation_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='landline',
            field=models.CharField(blank=True, help_text='Landline or alternative contact number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(db_column='activity_log_id', primary_key=True, serialize=False)),
                ('actor_role', models.CharField(blank=True, default='', max_length=20)),
                ('category', models.CharField(choices=[('security', 'Security'), ('users', 'Users'), ('requests', 'Requests'), ('tickets', 'Tickets'), ('inventory', 'Inventory'), ('settings', 'Settings'), ('sla', 'SLA'), ('communication', 'Communication'), ('system', 'System')], default='system', max_length=30)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('assign', 'Assign'), ('reschedule', 'Reschedule'), ('complete', 'Complete'), ('cancel', 'Cancel'), ('error', 'Error'), ('system', 'System')], max_length=30)),
                ('target_app_label', models.CharField(blank=True, default='', max_length=100)),
                ('target_model', models.CharField(blank=True, default='', max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('metadata', afn_service_management.fields.StructuredTextField(blank=True, default=dict, structure='dict')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('actor_display_name', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='activity_category_time_idx'), models.Index(fields=['action', 'created_at'], name='activity_action_time_idx'), models.Index(fields=['target_model', 'target_id'], name='activity_target_idx'), models.Index(fields=['actor', 'created_at'], name='activity_actor_time_idx')],
            },
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='preferred_work_areas',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
    ]
