# Generated by Django 5.2.13 on 2026-06-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_email_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='sms_notifications_enabled',
        ),
    ]
