# Generated by Django 6.0.3 on 2026-06-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_adminsettings_sms_notifications_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='id',
            field=models.BigAutoField(db_column='activity_log_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='id',
            field=models.BigAutoField(db_column='admin_settings_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='id',
            field=models.BigAutoField(db_column='change_log_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='id',
            field=models.BigAutoField(db_column='client_profile_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='managementprofile',
            name='id',
            field=models.BigAutoField(db_column='management_profile_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='id',
            field=models.BigAutoField(db_column='technician_profile_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(db_column='user_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercapabilitygrant',
            name='id',
            field=models.BigAutoField(db_column='user_capability_grant_id', primary_key=True, serialize=False),
        ),
    ]
