# Generated by Django 6.0.6 on 2026-06-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_pending_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='field_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
