# Generated by Django 6.0.6 on 2026-06-23 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_changelog_action_alter_changelog_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='arrival_radius_meters',
            field=models.PositiveSmallIntegerField(default=30, help_text='Maximum allowed distance (meters) between technician and service location.'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='location_validation_disabled_reason',
            field=models.TextField(blank=True, default='', help_text='Required when the superadmin disables location validation.'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='location_validation_enabled',
            field=models.BooleanField(default=True, help_text='When ON, technicians must be within the allowed radius to mark arrival.'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='location_validation_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='location_validation_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_validation_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
