# Generated by Django 6.0.6 on 2026-06-25 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_arrival_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='arrival_radius_meters',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='location_validation_disabled_reason',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='location_validation_enabled',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='location_validation_updated_at',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='location_validation_updated_by',
        ),
    ]
