# Generated by Django 6.0.6 on 2026-06-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_restore_arrival_validation_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='landline',
            field=models.CharField(blank=True, help_text='Landline or alternative contact number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
