# Generated by Django 6.0.6 on 2026-07-01 04:05

import afn_service_management.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_user_landline_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='metadata',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=dict, structure='dict'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='preferred_work_areas',
            field=afn_service_management.fields.StructuredTextField(blank=True, default=list, structure='list'),
        ),
    ]
